#!/usr/bin/env bats
# gaia-config-ci-regenerate.bats — E71-S4
#
# Tests for /gaia-config-ci --regenerate backup-and-prompt UX + user-steps
# include pattern. Covers TS-01..TS-12 mapping to AC1..AC10.
#
# Test cases:
#   TC-RSV2-CI-3 (AC1, AC2, AC3, AC4, AC5, AC9, AC10) — header + manual-edit detect + backup prompt + stale flag + post-edit prompt
#   TC-RSV2-CI-4 (AC6, AC7, AC8) — user-steps include + write-protection + scaffold

setup() {
  REPO_ROOT="$(cd "$BATS_TEST_DIRNAME/../.." && pwd)"
  SCRIPTS_DIR="$REPO_ROOT/plugins/gaia/scripts"
  SKILL_FILE="$REPO_ROOT/plugins/gaia/skills/gaia-ci-setup/SKILL.md"
  TEST_TMPDIR="$(mktemp -d)"
}

teardown() {
  if [ -n "${TEST_TMPDIR:-}" ] && [ -d "$TEST_TMPDIR" ]; then
    rm -rf "$TEST_TMPDIR"
  fi
}

# ---------------- AC1 / TS-01: Generated header ------------------

@test "AC1 (TS-01) — ci-regen-header.sh emits four-line header with sha256 + ISO-8601 timestamp" {
  local helper="$SCRIPTS_DIR/lib/ci-regen-header.sh"
  [ -x "$helper" ]
  local hdr
  hdr="$(bash "$helper" emit "abc123def456" 2>&1)"
  # Attribution line
  echo "$hdr" | grep -F "# Generated by /gaia-config-ci from project-config.yaml"
  # DO NOT EDIT warning referencing --regenerate
  echo "$hdr" | grep -F "# DO NOT EDIT"
  echo "$hdr" | grep -F -- "--regenerate"
  # Source hash line
  echo "$hdr" | grep -E "^# Source hash: sha256:[0-9a-f]+$"
  # Generated-at ISO-8601 timestamp
  echo "$hdr" | grep -E "^# Generated at: [0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}"
}

@test "AC1 — ci-regen-header.sh emit accepts a hash argument and embeds it in the Source hash line" {
  local helper="$SCRIPTS_DIR/lib/ci-regen-header.sh"
  local hdr
  hdr="$(bash "$helper" emit "deadbeefcafe")"
  echo "$hdr" | grep -F "Source hash: sha256:deadbeefcafe"
}

@test "AC1 — ci-regen-header.sh hash subcommand computes deterministic sha256 over stdin" {
  local helper="$SCRIPTS_DIR/lib/ci-regen-header.sh"
  local h1 h2
  h1="$(printf 'foo\nbar\n' | bash "$helper" hash)"
  h2="$(printf 'foo\nbar\n' | bash "$helper" hash)"
  [ -n "$h1" ]
  [ "$h1" = "$h2" ]
  echo "$h1" | grep -E "^[0-9a-f]{64}$"
}

# ---------------- AC2 / TS-02: Manual-edit detection -------------

@test "AC2 (TS-02) — ci-regen-detect-edit.sh exits 0 (clean) when body hash matches header hash" {
  local detect="$SCRIPTS_DIR/ci-regen-detect-edit.sh"
  local helper="$SCRIPTS_DIR/lib/ci-regen-header.sh"
  [ -x "$detect" ]

  # Prepare a body, hash it, then assemble header + body.
  local body="$TEST_TMPDIR/body.yml"
  printf 'jobs:\n  build:\n    runs-on: ubuntu-latest\n' > "$body"
  local body_hash
  body_hash="$(bash "$helper" hash < "$body")"

  local target="$TEST_TMPDIR/clean.yml"
  bash "$helper" emit "$body_hash" > "$target"
  cat "$body" >> "$target"

  run bash "$detect" "$target"
  [ "$status" -eq 0 ]
}

@test "AC2 — ci-regen-detect-edit.sh exits 1 (manually-edited) when body has been modified" {
  local detect="$SCRIPTS_DIR/ci-regen-detect-edit.sh"
  local helper="$SCRIPTS_DIR/lib/ci-regen-header.sh"

  local body="$TEST_TMPDIR/body.yml"
  printf 'jobs:\n  build:\n    runs-on: ubuntu-latest\n' > "$body"
  local body_hash
  body_hash="$(bash "$helper" hash < "$body")"

  local target="$TEST_TMPDIR/edited.yml"
  bash "$helper" emit "$body_hash" > "$target"
  cat "$body" >> "$target"
  # Tamper.
  printf 'extra: line\n' >> "$target"

  run bash "$detect" "$target"
  [ "$status" -eq 1 ]
}

@test "AC2 — ci-regen-detect-edit.sh exits 2 when header is missing (no Source hash line)" {
  local detect="$SCRIPTS_DIR/ci-regen-detect-edit.sh"
  local target="$TEST_TMPDIR/no-header.yml"
  printf 'jobs:\n  build: {}\n' > "$target"

  run bash "$detect" "$target"
  [ "$status" -eq 2 ]
}

# ---------------- AC3 / TS-03: Backup-or-merge prompt ------------

@test "AC3 (TS-03) — SKILL.md documents four backup-prompt options d/b/m/f with default b" {
  [ -f "$SKILL_FILE" ]
  # All four option letters surface in the regen section.
  grep -F "show diff" "$SKILL_FILE"
  grep -F "backup" "$SKILL_FILE"
  grep -F "cancel" "$SKILL_FILE"
  grep -F "force overwrite" "$SKILL_FILE"
  # Default is `b`.
  grep -E "[Dd]efault[^a-zA-Z]+(option )?b\b|default.*\bb\b" "$SKILL_FILE"
}

# ---------------- AC4 / TS-04: Backup directory ------------------

@test "AC4 (TS-04) — ci-regen-backup.sh copies workflow file to .gaia-backup/{ci-file}-{ts}/" {
  local backup="$SCRIPTS_DIR/ci-regen-backup.sh"
  [ -x "$backup" ]

  cd "$TEST_TMPDIR"
  mkdir -p .github/workflows
  printf 'jobs: {}\n' > .github/workflows/gaia-pre-merge.yml

  run bash "$backup" .github/workflows/gaia-pre-merge.yml
  [ "$status" -eq 0 ]
  # Output line names the backup directory.
  echo "$output" | grep -E '\.gaia-backup/gaia-pre-merge\.yml-[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:?[0-9]{2}:?[0-9]{2}'
  # Backup directory exists at project root with the file inside.
  local backup_dir
  backup_dir="$(ls -d .gaia-backup/gaia-pre-merge.yml-* 2>/dev/null | head -1)"
  [ -n "$backup_dir" ]
  [ -f "$backup_dir/gaia-pre-merge.yml" ]
  # Original file still in place (caller is responsible for replacing it).
  [ -f .github/workflows/gaia-pre-merge.yml ]
}

# ---------------- AC5 / TS-05: No prompt on clean -----------------

@test "AC5 (TS-05) — SKILL.md describes silent regen path when no manual edits detected" {
  grep -E "no.*prompt|silent|in-place" "$SKILL_FILE"
  grep -F "no manual edit" "$SKILL_FILE"
}

# ---------------- AC6 / TS-06: User-steps stitched ----------------

@test "AC6 (TS-06) — ci-regen-user-steps.sh discovers sibling *.user-steps.yml" {
  local us="$SCRIPTS_DIR/ci-regen-user-steps.sh"
  [ -x "$us" ]

  cd "$TEST_TMPDIR"
  mkdir -p .github/workflows
  printf 'jobs: {}\n' > .github/workflows/gaia-pre-merge.yml
  cat > .github/workflows/gaia-pre-merge.user-steps.yml <<'YAML'
steps_before_gaia:
  - name: Custom pre-step
    run: echo before
steps_after_gaia:
  - name: Custom post-step
    run: echo after
YAML

  run bash "$us" discover .github/workflows/gaia-pre-merge.yml
  [ "$status" -eq 0 ]
  echo "$output" | grep -F ".github/workflows/gaia-pre-merge.user-steps.yml"
}

@test "AC6 — ci-regen-user-steps.sh extract-before emits steps_before_gaia entries" {
  local us="$SCRIPTS_DIR/ci-regen-user-steps.sh"
  cd "$TEST_TMPDIR"
  mkdir -p .github/workflows
  cat > .github/workflows/gaia-pre-merge.user-steps.yml <<'YAML'
steps_before_gaia:
  - name: Custom pre-step
    run: echo before
steps_after_gaia: []
YAML

  run bash "$us" extract-before .github/workflows/gaia-pre-merge.user-steps.yml
  [ "$status" -eq 0 ]
  echo "$output" | grep -F "Custom pre-step"
  # Should NOT include the after-step section.
  ! echo "$output" | grep -F "echo after"
}

@test "AC6 — ci-regen-user-steps.sh extract-after emits steps_after_gaia entries" {
  local us="$SCRIPTS_DIR/ci-regen-user-steps.sh"
  cd "$TEST_TMPDIR"
  mkdir -p .github/workflows
  cat > .github/workflows/gaia-pre-merge.user-steps.yml <<'YAML'
steps_before_gaia: []
steps_after_gaia:
  - name: Custom post-step
    run: echo after
YAML

  run bash "$us" extract-after .github/workflows/gaia-pre-merge.user-steps.yml
  [ "$status" -eq 0 ]
  echo "$output" | grep -F "Custom post-step"
}

# ---------------- AC7 / TS-07: User-steps never overwritten ------

@test "AC7 (TS-07) — ci-regen-user-steps.sh treats user-steps file as read-only (write-protect helper)" {
  local us="$SCRIPTS_DIR/ci-regen-user-steps.sh"
  cd "$TEST_TMPDIR"
  mkdir -p .github/workflows
  cat > .github/workflows/gaia-pre-merge.user-steps.yml <<'YAML'
steps_before_gaia: []
steps_after_gaia: []
YAML
  local before_hash after_hash
  before_hash="$(shasum -a 256 .github/workflows/gaia-pre-merge.user-steps.yml | cut -d' ' -f1)"

  # Run all sub-commands that COULD touch the file.
  bash "$us" discover .github/workflows/gaia-pre-merge.yml >/dev/null
  bash "$us" extract-before .github/workflows/gaia-pre-merge.user-steps.yml >/dev/null
  bash "$us" extract-after .github/workflows/gaia-pre-merge.user-steps.yml >/dev/null

  after_hash="$(shasum -a 256 .github/workflows/gaia-pre-merge.user-steps.yml | cut -d' ' -f1)"
  [ "$before_hash" = "$after_hash" ]
}

@test "AC7 — write-protect mode rejects writes to *.user-steps.yml paths" {
  local us="$SCRIPTS_DIR/ci-regen-user-steps.sh"
  cd "$TEST_TMPDIR"
  mkdir -p .github/workflows
  cat > .github/workflows/gaia-pre-merge.user-steps.yml <<'YAML'
steps_before_gaia: []
steps_after_gaia: []
YAML

  # `assert-protected` MUST exit non-zero with an explanatory message —
  # callers use this as a guard before attempting any write op.
  run bash "$us" assert-protected .github/workflows/gaia-pre-merge.user-steps.yml
  [ "$status" -ne 0 ]
  echo "$output$stderr" | grep -iE "user-steps.*never modified|protected"
}

# ---------------- AC8 / TS-08: Scaffold on first run -------------

@test "AC8 (TS-08) — ci-regen-user-steps.sh scaffold creates commented template alongside missing file" {
  local us="$SCRIPTS_DIR/ci-regen-user-steps.sh"
  cd "$TEST_TMPDIR"
  mkdir -p .github/workflows
  printf 'jobs: {}\n' > .github/workflows/gaia-pre-merge.yml

  run bash "$us" scaffold .github/workflows/gaia-pre-merge.yml
  [ "$status" -eq 0 ]
  [ -f .github/workflows/gaia-pre-merge.user-steps.yml ]
  # Empty arrays plus YAML comments.
  grep -E "^steps_before_gaia: \[\]" .github/workflows/gaia-pre-merge.user-steps.yml
  grep -E "^steps_after_gaia: \[\]" .github/workflows/gaia-pre-merge.user-steps.yml
  grep -E "^# " .github/workflows/gaia-pre-merge.user-steps.yml
}

@test "AC8 — scaffold is a no-op when *.user-steps.yml already exists (file untouched)" {
  local us="$SCRIPTS_DIR/ci-regen-user-steps.sh"
  cd "$TEST_TMPDIR"
  mkdir -p .github/workflows
  printf 'jobs: {}\n' > .github/workflows/gaia-pre-merge.yml
  printf 'custom: content\n' > .github/workflows/gaia-pre-merge.user-steps.yml
  local before
  before="$(shasum -a 256 .github/workflows/gaia-pre-merge.user-steps.yml | cut -d' ' -f1)"

  run bash "$us" scaffold .github/workflows/gaia-pre-merge.yml
  [ "$status" -eq 0 ]

  local after
  after="$(shasum -a 256 .github/workflows/gaia-pre-merge.user-steps.yml | cut -d' ' -f1)"
  [ "$before" = "$after" ]
}

# ---------------- AC9 / TS-09..TS-11: Stale flag -----------------

@test "AC9 (TS-09) — ci-regen-stale-flag.sh write creates .gaia/memory/.config-stale" {
  local sf="$SCRIPTS_DIR/ci-regen-stale-flag.sh"
  [ -x "$sf" ]
  cd "$TEST_TMPDIR"
  mkdir -p .gaia/memory

  run bash "$sf" write
  [ "$status" -eq 0 ]
  [ -f .gaia/memory/.config-stale ]
}

@test "AC9 (TS-10) — ci-regen-stale-flag.sh check exits 0 when flag present, prints warning to stderr" {
  local sf="$SCRIPTS_DIR/ci-regen-stale-flag.sh"
  cd "$TEST_TMPDIR"
  mkdir -p .gaia/memory
  : > .gaia/memory/.config-stale

  run bash "$sf" check
  [ "$status" -eq 0 ]
  echo "$output$stderr" | grep -F -- "--regenerate"
}

@test "AC9 — ci-regen-stale-flag.sh check exits 1 when flag absent (silent)" {
  local sf="$SCRIPTS_DIR/ci-regen-stale-flag.sh"
  cd "$TEST_TMPDIR"
  mkdir -p .gaia/memory

  run bash "$sf" check
  [ "$status" -eq 1 ]
}

@test "AC9 (TS-11) — ci-regen-stale-flag.sh clear removes the flag file" {
  local sf="$SCRIPTS_DIR/ci-regen-stale-flag.sh"
  cd "$TEST_TMPDIR"
  mkdir -p .gaia/memory
  : > .gaia/memory/.config-stale

  run bash "$sf" clear
  [ "$status" -eq 0 ]
  [ ! -e .gaia/memory/.config-stale ]
}

@test "AC9 — ci-regen-stale-flag.sh clear is idempotent when flag already absent" {
  local sf="$SCRIPTS_DIR/ci-regen-stale-flag.sh"
  cd "$TEST_TMPDIR"
  mkdir -p .gaia/memory
  run bash "$sf" clear
  [ "$status" -eq 0 ]
  [ ! -e .gaia/memory/.config-stale ]
}

# ---------------- AC10 / TS-12: Post-edit prompt -----------------

@test "AC10 (TS-12) — ci-regen-post-edit-prompt.sh print emits three-option prompt y/n/d" {
  local pe="$SCRIPTS_DIR/ci-regen-post-edit-prompt.sh"
  [ -x "$pe" ]

  run bash "$pe" print
  [ "$status" -eq 0 ]
  echo "$output" | grep -F "regenerate now"
  echo "$output" | grep -F "defer"
  echo "$output" | grep -F "show diff"
  # Three-letter option markers.
  echo "$output" | grep -E '\(y\)|\[y\]'
  echo "$output" | grep -E '\(n\)|\[n\]'
  echo "$output" | grep -E '\(d\)|\[d\]'
}

@test "AC10 — ci-regen-post-edit-prompt.sh handle y triggers regeneration path" {
  local pe="$SCRIPTS_DIR/ci-regen-post-edit-prompt.sh"
  run bash "$pe" handle y
  [ "$status" -eq 0 ]
  echo "$output" | grep -i "regenerate"
}

@test "AC10 — ci-regen-post-edit-prompt.sh handle n writes the stale flag" {
  local pe="$SCRIPTS_DIR/ci-regen-post-edit-prompt.sh"
  cd "$TEST_TMPDIR"
  mkdir -p .gaia/memory

  run bash "$pe" handle n
  [ "$status" -eq 0 ]
  [ -f .gaia/memory/.config-stale ]
}

@test "AC10 — ci-regen-post-edit-prompt.sh handle d emits diff hint" {
  local pe="$SCRIPTS_DIR/ci-regen-post-edit-prompt.sh"
  run bash "$pe" handle d
  [ "$status" -eq 0 ]
  echo "$output" | grep -iF "diff"
}

# ---------------- SKILL.md surface ----------------

@test "SKILL.md documents --regenerate flag" {
  grep -F -- "--regenerate" "$SKILL_FILE"
}

@test "SKILL.md documents user-steps include pattern" {
  grep -F "user-steps.yml" "$SKILL_FILE"
}

@test "SKILL.md references the .gaia-backup directory convention" {
  grep -F ".gaia-backup" "$SKILL_FILE"
}

@test "gaia-help.csv lists --regenerate hint row" {
  local csv="$REPO_ROOT/plugins/gaia/knowledge/gaia-help.csv"
  grep -F -- "--regenerate" "$csv"
}
