#!/usr/bin/env bash
# subcmd-scaffold.sh — /gaia-test-automate --scaffold sub-command
#
# Generates SCAFFOLD-ONLY test skeletons for unmapped acceptance criteria
# in a story. The skeletons intentionally contain placeholder patterns
# (test.skip / expect(true) / assert True) so the deterministic
# placeholder-test-detector.sh treats them as low_quality_test_generated.
#
# Hard invariant:
#   This script MUST NEVER update the Review Gate Test Automation row to
#   PASSED. It explicitly logs "review gate not updated" on stdout so the
#   /gaia-test-automate skill body can observe the contract.
#
# Usage:
#   subcmd-scaffold.sh \
#     --story-file <path> \
#     --out-dir <path> \
#     [--stack {ts-dev|python-dev|java-dev|go-dev|flutter-dev|angular-dev}]
#
#   subcmd-scaffold.sh --help
#
# Exit codes:
#   0 — skeletons generated successfully
#   1 — story file missing / unreadable
#   2 — caller error (missing required flag)

set -euo pipefail
LC_ALL=C
export LC_ALL

SCRIPT_NAME="subcmd-scaffold.sh"

err() { printf '%s: error: %s\n' "$SCRIPT_NAME" "$*" >&2; }

usage() {
  cat <<EOF
$SCRIPT_NAME — /gaia-test-automate --scaffold sub-command.

Usage:
  $SCRIPT_NAME \\
    --story-file <path> \\
    --out-dir <path> \\
    [--stack {ts-dev|python-dev|java-dev|go-dev|flutter-dev|angular-dev}]

Generates placeholder test skeletons for unmapped ACs. Review Gate is
NEVER updated to PASSED — the skill body MUST observe this contract.
EOF
}

STORY_FILE=""
OUT_DIR=""
STACK="ts-dev"

while [ $# -gt 0 ]; do
  case "$1" in
    --story-file) STORY_FILE="${2:-}"; shift 2 ;;
    --out-dir)    OUT_DIR="${2:-}";    shift 2 ;;
    --stack)      STACK="${2:-}";      shift 2 ;;
    -h|--help)    usage; exit 0 ;;
    *)            err "unknown argument: $1"; usage >&2; exit 2 ;;
  esac
done

[ -n "$STORY_FILE" ] || { err "missing required --story-file"; exit 2; }
[ -n "$OUT_DIR" ]    || { err "missing required --out-dir";    exit 2; }
[ -r "$STORY_FILE" ] || { err "story file not readable: $STORY_FILE"; exit 1; }

mkdir -p "$OUT_DIR"

# ---------------------------------------------------------------------------
# Resolve story key.
# ---------------------------------------------------------------------------
story_key="$(awk '
  /^---$/ { fm = !fm; next }
  fm && /^key:/ {
    s = $0; sub(/^key:[[:space:]]*/, "", s); gsub(/"/, "", s); print s; exit
  }
' "$STORY_FILE")"
if [ -z "$story_key" ]; then
  story_key="$(basename "$STORY_FILE" .md | grep -oE '^E[0-9]+-S[0-9]+' || true)"
fi
[ -n "$story_key" ] || story_key="UNKNOWN"

# ---------------------------------------------------------------------------
# Enumerate ACs (mapped to TC) so we know which ones are mapped.
# ---------------------------------------------------------------------------
mapped_acs="$(awk '
  /^## Test Cases/ { in_tc=1; next }
  in_tc && /^## / { in_tc=0 }
  in_tc && /^\|/ {
    if ($0 ~ /^\|[[:space:]]*TC[[:space:]]*\|/) next
    if ($0 ~ /^\|[-: ]+\|/) next
    n = split($0, c, "|")
    if (n < 5) next
    ac=c[3]
    gsub(/^[[:space:]]+|[[:space:]]+$/, "", ac)
    if (ac != "") print ac
  }
' "$STORY_FILE")"

all_acs="$(awk '
  /^## Acceptance Criteria/ { in_ac=1; next }
  in_ac && /^## / { in_ac=0 }
  in_ac && /^- \[[ x]\] AC[0-9]+/ {
    s=$0; sub(/^- \[[ x]\] /, "", s)
    n=index(s, ":"); if (n>0) ac=substr(s, 1, n-1); else ac=s
    print ac
  }
' "$STORY_FILE")"

# ---------------------------------------------------------------------------
# Choose a per-stack file extension and skeleton body. Each skeleton
# contains a placeholder pattern that placeholder-test-detector.sh will
# flag as low_quality_test_generated.
# ---------------------------------------------------------------------------
case "$STACK" in
  ts-dev|angular-dev) ext="test.ts"  ; lang="ts"      ;;
  python-dev)         ext="test.py"  ; lang="python"  ;;
  java-dev)           ext="Test.java"; lang="java"    ;;
  go-dev)             ext="_test.go" ; lang="go"      ;;
  flutter-dev)        ext="test.dart"; lang="dart"    ;;
  *)                  ext="test.ts"  ; lang="ts"      ;;
esac

generated=0
while IFS= read -r ac; do
  [ -n "$ac" ] || continue
  if printf '%s\n' "$mapped_acs" | grep -qFx "$ac"; then continue; fi

  outfile="$OUT_DIR/${story_key}-${ac}.${ext}"
  case "$lang" in
    ts)
      cat >"$outfile" <<EOF
// SCAFFOLD: ${story_key} ${ac}
// Generated by /gaia-test-automate --scaffold; flesh out before merging.
import { describe, test } from 'vitest';

describe('${story_key} ${ac}', () => {
  test.skip('TODO: implement ${ac}', () => {
    // TODO: replace with real assertion
    expect(true).toBe(true);
  });
});
EOF
      ;;
    python)
      cat >"$outfile" <<EOF
# SCAFFOLD: ${story_key} ${ac}
# Generated by /gaia-test-automate --scaffold; flesh out before merging.
import pytest


@pytest.mark.skip(reason="TODO: implement ${ac}")
def test_${ac}_placeholder():
    # TODO: replace with real assertion
    assert True
EOF
      ;;
    java)
      cat >"$outfile" <<EOF
// SCAFFOLD: ${story_key} ${ac}
// Generated by /gaia-test-automate --scaffold; flesh out before merging.
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ${story_key}_${ac}Test {
    @Test
    @Disabled("TODO: implement ${ac}")
    void placeholder() {
        // TODO: replace with real assertion
        assertTrue(true);
    }
}
EOF
      ;;
    go)
      cat >"$outfile" <<EOF
// SCAFFOLD: ${story_key} ${ac}
// Generated by /gaia-test-automate --scaffold; flesh out before merging.
package scaffold

import "testing"

func Test_${ac}_Placeholder(t *testing.T) {
    t.Skip("TODO: implement ${ac}")
}
EOF
      ;;
    dart)
      cat >"$outfile" <<EOF
// SCAFFOLD: ${story_key} ${ac}
// Generated by /gaia-test-automate --scaffold; flesh out before merging.
import 'package:test/test.dart';

void main() {
  test('${story_key} ${ac} placeholder', () {
    // TODO: replace with real assertion
    expect(true, isTrue);
  }, skip: 'TODO: implement ${ac}');
}
EOF
      ;;
  esac
  generated=$((generated+1))
done <<<"$all_acs"

# ---------------------------------------------------------------------------
# Hard invariant — emit the contract marker on stdout. The skill body and
# bats tests rely on this exact phrase.
# ---------------------------------------------------------------------------
printf 'scaffold: %d skeleton(s) generated for %s under %s\n' \
  "$generated" "$story_key" "$OUT_DIR"
printf 'scaffold: review gate not updated (skeleton-only output is not coverage)\n'

exit 0
