#!/usr/bin/env bash
# generate-config.sh — convert a JSON answer-bundle (stdin) into a complete
# .gaia/config/project-config.yaml at the target project root.
# Story: E71-S1 (FR-RSV2-34, AC2). Deterministic per ADR-042.
#
# Atomic write: serialize to <target>.tmp first, then rename. Refuses to
# clobber an existing config (greenfield invariant — AC4).
#
# Input JSON shape (all keys optional unless noted):
#   {
#     "project_shape": "single backend|microservices|mobile only|mobile+backend|microservices+mobile",
#     "stacks": [{"name": "...", "language": "...", "paths": ["..."]}, ...],
#     "compliance": {"regimes": ["gdpr", ...], "ui_present": true},
#     "environments": {"<env>": {"url": "...", "credentials": {"<key>": "<ENV_VAR_NAME>"}}, ...},
#     "ci_platform": {"provider": "github-actions|none|...", "pipeline": "..."},
#     "platforms": ["ios"|"android"|"web", ...],
#     "device_targets": {"ios": ["iPhone 15"], ...}
#   }
#
# Usage:
#   generate-config.sh --path <project-root> --name <project-name> < answers.json
#
# Exit codes:
#   0  Wrote .gaia/config/project-config.yaml.
#   1  Refused to clobber existing config (greenfield invariant).
#   2  Usage error / malformed input.

set -euo pipefail
LC_ALL=C
export LC_ALL

SCRIPT_NAME="gaia-init/generate-config.sh"

target=""
name=""
phase="full"   # E85-S3: default phase = full (backward compat). --phase minimal
               #         emits the Phase 0 5-field bootstrap surface.

while [ $# -gt 0 ]; do
  case "$1" in
    --path)
      [ $# -ge 2 ] || { printf '%s: --path requires a value\n' "$SCRIPT_NAME" >&2; exit 2; }
      target="$2"; shift 2 ;;
    --name)
      [ $# -ge 2 ] || { printf '%s: --name requires a value\n' "$SCRIPT_NAME" >&2; exit 2; }
      name="$2"; shift 2 ;;
    --phase)
      [ $# -ge 2 ] || { printf '%s: --phase requires a value\n' "$SCRIPT_NAME" >&2; exit 2; }
      case "$2" in
        minimal|full) phase="$2" ;;
        *) printf "%s: --phase must be 'minimal' or 'full' (got: %s)\n" "$SCRIPT_NAME" "$2" >&2; exit 2 ;;
      esac
      shift 2 ;;
    --help|-h) sed -n '1,30p' "$0"; exit 0 ;;
    *) printf '%s: unexpected argument: %s\n' "$SCRIPT_NAME" "$1" >&2; exit 2 ;;
  esac
done

[ -n "$target" ] || { printf '%s: --path is required\n' "$SCRIPT_NAME" >&2; exit 2; }
[ -n "$name" ]   || { printf '%s: --name is required\n' "$SCRIPT_NAME" >&2; exit 2; }

# E85-S3 / AC8 — resolve framework_version from the plugin manifest, not
# hardcoded. The script lives at plugins/gaia/skills/gaia-init/scripts/, so
# the manifest is three dirs up at .claude-plugin/plugin.json.
SCRIPT_DIR_ABS="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_MANIFEST="$SCRIPT_DIR_ABS/../../../.claude-plugin/plugin.json"
framework_version="unknown"
if [ -f "$PLUGIN_MANIFEST" ] && command -v python3 >/dev/null 2>&1; then
  framework_version="$(python3 -c "import json; print(json.load(open('$PLUGIN_MANIFEST'))['version'])" 2>/dev/null || echo "unknown")"
fi

# E96-S1 / ADR-111: new projects get config under .gaia/config/ (canonical
# post-migration layout). Legacy config/ is no longer the default for new
# installs — /gaia-migrate handles existing projects with the legacy layout.
mkdir -p -- "$target/.gaia/config"

cfg_path="$target/.gaia/config/project-config.yaml"
if [ -e "$cfg_path" ]; then
  printf '%s: refuses to overwrite existing config: %s\n' "$SCRIPT_NAME" "$cfg_path" >&2
  exit 1
fi

# Read stdin into a temp file so we can parse it with whichever tool is available.
in_json="$(mktemp -t gaia-init-answers.XXXXXX)"
trap 'rm -f -- "$in_json" 2>/dev/null || true' EXIT
cat > "$in_json"

# Resolve absolute path for project_root (POSIX-portable; falls back to as-is).
abs_target="$target"
if [ -d "$target" ]; then
  abs_target="$(cd "$target" && pwd)"
fi

# We deliberately avoid jq dependence — many GAIA installs are bare. A
# minimal Python fallback is used (Python 3 is available on every supported
# OS); if Python is also missing we fall back to a literal echo of stdin.
yaml_path="$cfg_path.tmp"

emit_yaml() {
  if command -v python3 >/dev/null 2>&1; then
    python3 - "$abs_target" "$name" "$in_json" "$yaml_path" "$phase" "$framework_version" <<'PYEOF'
import json, sys, os, datetime

abs_target, name, in_json, out_path, phase, framework_version = sys.argv[1:7]
with open(in_json) as f:
    data = json.load(f) if os.path.getsize(in_json) > 0 else {}

today = datetime.datetime.utcnow().strftime("%Y-%m-%d")

def yaml_quote(s):
    s = str(s)
    if s == "" or any(c in s for c in ":#&*!|>'\"%@`{}[],"):
        return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'
    return s

lines = []
lines.append("# project-config.yaml — generated by /gaia-init")
lines.append(f"# Project: {name}")
lines.append("#")
lines.append("# AF-2026-05-30-4 F-06 — portability note:")
lines.append("#   The path keys below are emitted as host-anchored ABSOLUTE paths so")
lines.append("#   the runtime resolver can find them regardless of the caller's cwd.")
lines.append("#   That makes the file machine-specific — a literal copy of it will")
lines.append("#   point at /Users/<author>/... on every other machine. The seeded")
lines.append("#   .gitignore therefore ignores .gaia/config/ as well as the rest of")
lines.append("#   the runtime tree (.gaia/memory/ + .gaia/state/) so the absolute-")
lines.append("#   path config never lands in a commit by accident. Each contributor")
lines.append("#   re-runs /gaia-init (or exports CLAUDE_PROJECT_ROOT before invoking")
lines.append("#   GAIA) on their machine to seed a local copy.")
lines.append("#   To intentionally commit a portable copy of this file, rewrite the")
lines.append("#   five path keys to be relative-to-cwd (e.g. .gaia/memory) AND")
lines.append("#   ensure every consumer is invoked from project_root.")
lines.append("")
lines.append(f"project_root: {abs_target}")
lines.append(f"project_path: {abs_target}")
lines.append(f"memory_path: {abs_target}/.gaia/memory")
lines.append(f"checkpoint_path: {abs_target}/.gaia/memory/checkpoints")
lines.append(f"installed_path: {abs_target}")
lines.append(f"framework_version: {yaml_quote(framework_version)}")
lines.append(f"date: {today}")

# E85-S3 / ADR-096 — schema_version + config_phase meta keys are written on
# every config (both Phase 0 minimal and the full discovery flow). The
# `--phase` argument selects which conditional sections are emitted below.
lines.append('schema_version: "2.0.0"')
lines.append(f"config_phase: {phase}")

# E85-S3 / FR-453 — Phase 0 user-facing keys. Always written; in the full
# flow these are still useful (project_name + project_kind + version +
# primary_platform exist regardless of phase).
project_name_val = data.get("project_name") or name
_pkind = data.get("project_kind") or "application"
# AF-2026-05-21-9: when project_shape == "claude-code-plugin", force
# project_kind up front. Applies to BOTH phase=full and phase=minimal so
# Phase 0 Quick setup users selecting "Claude Code plugin" as primary_platform
# get the canonical project_kind via SKILL.md Step 1b's alias-normalization
# arm setting project_shape in the bundle. The legacy plugin-shape block
# (lines ~158-160) is itself gated on `if phase == "full":` so removing
# this clause's phase gate cannot produce duplicate `project_kind:` entries
# in either phase.
if (data.get("project_shape") or "").strip() == "claude-code-plugin":
    _pkind = "claude-code-plugin"
project_kind_val = _pkind
version_val = data.get("version") or "0.1.0"
primary_platform_val = data.get("primary_platform") or ""
lines.append("")
lines.append(f"project_name: {yaml_quote(project_name_val)}")
lines.append(f"project_kind: {yaml_quote(project_kind_val)}")
lines.append(f"version: {yaml_quote(version_val)}")
if primary_platform_val:
    lines.append(f"primary_platform: {yaml_quote(primary_platform_val)}")

# E85-S3 / FR-453 — Phase 0 minimal short-circuits here. The conditional
# sections below (project_shape gate, stacks, compliance, environments,
# ci_platform, platforms, device_targets) are emitted ONLY in the full path
# per the schema v2.0.0 allOf-conditional contract (E85-S2 / ADR-096).
if phase == "full":
    project_shape = (data.get("project_shape") or "").strip()
    is_plugin_shape = project_shape == "claude-code-plugin"

    # E77-S9 / FR-411 — Claude Code plugin shape (option 6).
    # Seeds the canonical claude-code-plugin stack file (authored by E77-S2 /
    # FR-404) and plugin-specific tool_adapters defaults. Skips the per-service
    # iterative stacks loop because the plugin stack is single-shape. Out of
    # scope: multi-plugin marketplace (NOT seeded). `project_kind` is already
    # set above (E85-S3 forces it to "claude-code-plugin" when project_shape
    # matches), so no duplicate emission here.

    stacks = data.get("stacks") or []
    if is_plugin_shape:
        # Plugin shape: emit a single stack entry that names the plugin stack
        # file (resolver picks up config/stacks/claude-code-plugin.yaml).
        lines.append("")
        lines.append("stacks:")
        lines.append('  - name: "claude-code-plugin"')
        # No language / paths fields — the plugin stack file is the source of
        # truth for file_extensions / discovery_rules / casing /
        # frontmatter_requirements (see E77-S2 / FR-404).
    elif stacks:
        lines.append("")
        lines.append("stacks:")
        for s in stacks:
            lines.append(f"  - name: {yaml_quote(s.get('name', ''))}")
            lines.append(f"    language: {yaml_quote(s.get('language', ''))}")
            lines.append("    paths:")
            for p in s.get("paths", []) or []:
                # AF-2026-06-02-1 / Test16 F-M02 — normalize a bare dir
                # or trailing-slash path to `<dir>/**` so the brownfield
                # orchestrator's matches_glob() picks up every file under
                # the directory. The pre-fix form persisted the user's
                # `core/` answer verbatim, and the orchestrator's
                # per-stack file-list intersection then yielded 0 files
                # (matches_glob has the same bare-dir handling now, but
                # writing the canonical form here keeps the YAML
                # operator-readable and avoids relying on the consumer's
                # smart-match for the common case).
                norm = p
                if isinstance(norm, str) and norm:
                    has_glob = any(c in norm for c in "*?[")
                    if norm.endswith("/") or not has_glob:
                        norm = norm.rstrip("/") + "/**"
                lines.append(f"      - {yaml_quote(norm)}")
            # AF-2026-05-29-1 / Test08 F-4: preserve per-stack `excludes` so the
            # SR-87 default-exclude patterns documented in SKILL.md Step 2.3
            # (.env, secrets/, build/, dist/, node_modules/, .venv/, target/,
            # etc.) actually reach the generated config. Previously the script
            # iterated only name/language/paths and dropped excludes silently —
            # downstream brownfield + scan tooling missed the operator's intent.
            excludes = s.get("excludes") or []
            if excludes:
                lines.append("    excludes:")
                for ex in excludes:
                    lines.append(f"      - {yaml_quote(ex)}")

    # E77-S9 / FR-411 — plugin-specific tool_adapters defaults.
    # shellcheck: shell-script linting under plugins/gaia/scripts/.
    # bats: bats-core test suites under plugins/gaia/tests/.
    # markdownlint: SKILL.md / ADR / docs lint.
    # yamllint: manifest.yaml / config/*.yaml / rubric overlays.
    # Adapter implementations are introduced by E77-S11 / E77-S12 / E77-S13.
    if is_plugin_shape:
        lines.append("")
        lines.append("tool_adapters:")
        lines.append("  - shellcheck")
        lines.append("  - bats")
        lines.append("  - markdownlint")
        lines.append("  - yamllint")

    compliance = data.get("compliance") or {}
    # AF-2026-05-22-9 Bug-15: coerce list-form compliance (operator submits
    # `compliance: []` per a misreading of the questionnaire) into the
    # object form documented by the SKILL prompt. Empty list → empty object
    # (omitted from output). Non-empty list is treated as a regimes-array
    # under the canonical `{ regimes: [...] }` shape, preserving operator
    # intent without crashing on `.get()` against a `str`/`list`.
    if isinstance(compliance, list):
        compliance = {"regimes": compliance} if compliance else {}
    if compliance:
        lines.append("")
        lines.append("compliance:")
        regimes = compliance.get("regimes") or []
        if regimes:
            lines.append("  regimes:")
            for r in regimes:
                lines.append(f"    - {yaml_quote(r)}")
        if "ui_present" in compliance:
            lines.append(f"  ui_present: {'true' if compliance['ui_present'] else 'false'}")
        if compliance.get("domain"):
            lines.append(f"  domain: {yaml_quote(compliance['domain'])}")

    envs = data.get("environments") or {}
    # F-2 (AF-2026-05-26-2): mirror the list-form compliance coercion above.
    # An operator who submits `environments: []` (or a list, per a misreading
    # of the iterative questionnaire) previously crashed at `.items()` below
    # with `AttributeError: 'list' object has no attribute 'items'`. An empty
    # list collapses to {} (block omitted); a non-empty list cannot be mapped
    # to the {name: body} shape, so reject it with a clear message rather than
    # crash.
    if isinstance(envs, list):
        if not envs:
            envs = {}
        else:
            # AF-2026-05-29-1 / Test08 F-1: SKILL.md Step 2.6 documents the
            # environments answer-bundle as an iterative list of objects
            # `[{name, url, auth_type}, ...]` (matching how the questionnaire
            # collects them per-environment). Previously the script rejected
            # that documented form and silently dropped the operator's input.
            # Transparently transform it into the canonical mapping shape
            # `{name: {url, credentials: {token: auth_type}}}` so the
            # documented SKILL.md form actually round-trips through the
            # generator. A list entry without a `name` is the only true
            # error — those are skipped with a NOTICE.
            transformed = {}
            for entry in envs:
                if not isinstance(entry, dict):
                    sys.stderr.write(
                        f"generate-config.sh: environments[] entry is not an object "
                        f"({type(entry).__name__}); skipping.\n"
                    )
                    continue
                env_name = entry.get("name")
                if not env_name:
                    sys.stderr.write(
                        "generate-config.sh: environments[] entry has no `name`; "
                        "skipping.\n"
                    )
                    continue
                body = {}
                if entry.get("url"):
                    body["url"] = entry["url"]
                # auth_type → credentials.token mapping (env-var NAME, not
                # literal credential, per SKILL.md Step 2.6 contract).
                if entry.get("auth_type"):
                    body["credentials"] = {"token": entry["auth_type"]}
                # Pass through any other recognised fields (forward-compat).
                for k, v in entry.items():
                    if k not in ("name", "url", "auth_type", "credentials"):
                        body[k] = v
                if entry.get("credentials"):
                    body["credentials"] = entry["credentials"]
                transformed[env_name] = body
            envs = transformed
    # F-4 (AF-2026-05-26-2): schema allOf[2] (config_phase=full) requires a
    # populated `environments` block, but the questionnaire permits "no
    # environments". Seed a minimal `local` map-shape entry so a full-phase
    # config validates out of the box; the operator refines it later via
    # /gaia-config-env. Coupled with F-3 — both platforms and environments
    # are required by allOf[2] (ci_cd:{} is already emitted above).
    if phase == "full" and not envs:
        envs = {"local": {"url": "http://localhost"}}
        # F-001 (Test04): the inject is intentional (allOf[2] needs a populated
        # environments block), but the operator declared no environments — so
        # surface a NOTICE instead of silently overriding their input. They can
        # remove/edit it via /gaia-config-env.
        sys.stderr.write(
            "generate-config.sh: NOTICE — no environments were declared, but "
            "config_phase=full requires a populated environments block; seeded a "
            "default 'local' (http://localhost) on your behalf. Edit or remove it "
            "via /gaia-config-env.\n"
        )
    if envs:
        lines.append("")
        lines.append("environments:")
        for env_name, env_body in envs.items():
            lines.append(f"  {yaml_quote(env_name)}:")
            if "url" in env_body:
                lines.append(f"    url: {yaml_quote(env_body['url'])}")
            creds = env_body.get("credentials") or {}
            if creds:
                lines.append("    credentials:")
                for k, v in creds.items():
                    # v MUST be the env-var NAME, never a literal credential.
                    lines.append(f"      {yaml_quote(k)}: {yaml_quote(v)}")

    ci = data.get("ci_platform") or {}
    if ci.get("provider"):
        lines.append("")
        lines.append("ci_platform:")
        lines.append(f"  provider: {yaml_quote(ci['provider'])}")
        if ci.get("pipeline"):
            lines.append(f"  pipeline: {yaml_quote(ci['pipeline'])}")

    # AF-2026-05-22-9 Bug-1: the schema v2.0.0 full-phase allOf requires the
    # `ci_cd:` key (config-block for CI behavior — distinct from
    # `ci_platform:`, which is detection output). Emit an empty stub here so
    # the generated config validates against its own schema at phase=full.
    # /gaia-ci-setup later populates ci_cd.* with real settings.
    if phase == "full":
        lines.append("")
        lines.append("ci_cd: {}")

    platforms = data.get("platforms") or []
    # AF-2026-05-31-1 / Test12 F-02 + F-03: normalize the `backend` alias to
    # the canonical schema enum token `server`. The questionnaire SKILL.md
    # documents both as accepted vocabulary (Step 2b) — `backend` reads more
    # naturally in conversation, but the schema's platformId enum only knows
    # `server`. Normalize on the write side so users who type either spelling
    # produce a schema-valid config without the validator having to either
    # widen the enum or fail with "unknown platform".
    platforms = ["server" if (isinstance(p, str) and p.lower() == "backend") else p for p in platforms]
    # F-3 (AF-2026-05-26-2): schema allOf[2] (config_phase=full) requires a
    # non-empty `platforms` array. gaia-init never emits config_phase=partial
    # (only minimal|full), so the gap is full-phase only. For web-oriented
    # shapes that don't gather a platform list, default to [web] — `web` is in
    # the platformId enum and validate-platform-stack.sh returns 0 for web
    # unconditionally, so this default never trips the platform/stack gate.
    # AF-2026-05-29-2 / Test09 F-2: SKIP the [web] default when the operator
    # explicitly declared `ui_present: false` (headless backend, CLI, library,
    # service-only project). Defaulting headless projects to platforms:[web] is
    # actively misleading — it makes downstream platform-aware gates (a11y,
    # ux-design) treat the project as having a web UI when it doesn't. The
    # AF-26-2 F-3 default is preserved for actually-web-oriented shapes.
    if phase == "full" and not platforms:
        _shape = (data.get("project_shape") or "").strip().lower()
        _compliance = data.get("compliance") or {}
        if isinstance(_compliance, list):
            _compliance = {"regimes": _compliance} if _compliance else {}
        _ui_present_explicit_false = _compliance.get("ui_present") is False
        if _ui_present_explicit_false:
            # AF-2026-05-30-2 / Test10 F-05: emit platforms:[server] for
            # explicit headless declarations. Prior to F-05 the headless
            # branch left platforms empty, but the JSON schema's full-phase
            # `platforms` minItems:1 constraint then rejected the config —
            # meaning a headless service (the shape the brownfield tutorial
            # tells users to declare) was unrepresentable in a valid full
            # config. The `server` platformId was added to the enum to fill
            # this gap (Test10 F-05 fix).
            platforms = ["server"]
        elif _shape in ("web-app", "fullstack", "microservices", "application", ""):
            platforms = ["web"]
        elif _shape in ("single backend",):
            # "Single backend" is canonically headless even without an explicit
            # ui_present:false declaration. Same F-05 fix: emit ["server"]
            # so the full-phase config validates.
            platforms = ["server"]
        else:
            # AF-2026-05-30-4 / Test11 F-04: catch-all so a full-phase
            # config NEVER emits an empty platforms array (which fails
            # schema minItems:1). The prior branches handled web-oriented
            # shapes + explicit headless + single-backend, but any shape
            # outside those lists (e.g. "library", "cli", "service",
            # "single-backend" with a hyphen, or a typo) fell through with
            # platforms empty and the generated config was schema-invalid.
            # Default to ["server"] — headless is the safest assumption
            # when the shape's UI surface is unknown; operators with a
            # real UI shape can still override via /gaia-config-platform.
            platforms = ["server"]
    if platforms:
        lines.append("")
        lines.append("platforms:")
        for p in platforms:
            lines.append(f"  - {yaml_quote(p)}")

    device_targets = data.get("device_targets") or {}
    if device_targets:
        lines.append("")
        lines.append("device_targets:")
        for plat, body in device_targets.items():
            lines.append(f"  {yaml_quote(plat)}:")
            # Two shapes accepted:
            #   1. Canonical (E74-S11): dict with os_versions / form_factors /
            #      screen_sizes per ADR-081 / project-config.schema.json.
            #   2. Legacy (E71-S1): list of device-name strings.
            if isinstance(body, dict):
                ov = body.get("os_versions") or []
                ff = body.get("form_factors") or []
                ss = body.get("screen_sizes") or []
                if ov:
                    lines.append("    os_versions:")
                    for v in ov:
                        # os_versions are schema-required strings; force quoting so
                        # values like "16.0" do not round-trip as YAML floats.
                        s = str(v).replace('\\', '\\\\').replace('"', '\\"')
                        lines.append(f'      - "{s}"')
                if ff:
                    lines.append("    form_factors:")
                    for v in ff:
                        lines.append(f"      - {yaml_quote(v)}")
                if ss:
                    lines.append("    screen_sizes:")
                    for s in ss:
                        if isinstance(s, dict):
                            lines.append(
                                f"      - {{ width: {int(s['width'])}, "
                                f"height: {int(s['height'])}, "
                                f"density: {s['density']} }}"
                            )
                        else:
                            # Pass-through string (rare).
                            lines.append(f"      - {yaml_quote(s)}")
            else:
                # Legacy list-of-strings shape.
                for d in body or []:
                    lines.append(f"    - {yaml_quote(d)}")

with open(out_path, "w") as f:
    f.write("\n".join(lines) + "\n")
PYEOF
  else
    # Python 3 unavailable — emit a minimal valid config. The rich path is
    # the supported path; this fallback exists only so the script does not
    # hard-fail on stripped-down environments.
    cat > "$yaml_path" <<EOF
# project-config.yaml — generated by /gaia-init (minimal fallback)
# Project: $name

project_root: $abs_target
project_path: $abs_target
memory_path: $abs_target/.gaia/memory
checkpoint_path: $abs_target/.gaia/memory/checkpoints
installed_path: $abs_target
framework_version: 0.0.0
date: $(date -u +"%Y-%m-%d")
EOF
  fi
}

emit_yaml
mv -f -- "$yaml_path" "$cfg_path"

# ---------- .gitignore seed (Test05 F-055) ----------
# A fresh project has no .gitignore, so the first `git add -A` pulls in macOS
# .DS_Store, editor swap files, and the .gaia/ runtime tree. Seed a sensible
# default. Non-destructive: create only when absent; if one already exists,
# append a GAIA block ONCE (idempotent — keyed on the marker line). The .gaia/
# runtime tree is NOT committed (it is local runtime state per ADR-111); the
# product source lives under gaia-public/ and is tracked separately.
gitignore_path="$target/.gitignore"
gaia_marker="# --- GAIA (added by /gaia-init) ---"
gaia_block="$gaia_marker
.DS_Store
**/.DS_Store
*.swp
*.swo
*~
.idea/
.vscode/
# AF-2026-06-02-1 / Test16 F-L04 — Python test-runner artifacts.
# /gaia-bridge-enable + /gaia-run-tests dispatch pytest, which writes
# .coverage / .pytest_cache/ / __pycache__/ at the project root. Without
# these lines a fresh project's first `git add -A` after a bridge run
# pulls them in by accident.
.coverage
.coverage.*
.pytest_cache/
__pycache__/
*.py[cod]
# GAIA runtime tree is local state, not source — do not commit.
# AF-2026-05-30-4 F-06: .gaia/config/ is also ignored because the
# /gaia-init-generated project-config.yaml carries host-anchored absolute
# paths (see the portability note at the top of project-config.yaml) — a
# literal commit would break clones and CI. Each contributor re-seeds the
# config locally by re-running /gaia-init.
.gaia/memory/
.gaia/state/
.gaia/config/"
if [ ! -e "$gitignore_path" ]; then
  printf '%s\n' "$gaia_block" > "$gitignore_path"
  printf '%s: seeded %s (.DS_Store, editor junk, .gaia/ runtime state)\n' "$SCRIPT_NAME" "$gitignore_path" >&2
elif ! grep -qF "$gaia_marker" "$gitignore_path" 2>/dev/null; then
  printf '\n%s\n' "$gaia_block" >> "$gitignore_path"
  printf '%s: appended GAIA block to existing %s\n' "$SCRIPT_NAME" "$gitignore_path" >&2
else
  # AF-2026-05-31-1 / Test12 F-09 — back-fill missing .gaia/ entries on an
  # already-marked block. Older GAIA versions (pre-AF-2026-05-30-4) seeded a
  # block that listed only `.gaia/memory/` + `.gaia/state/` — the host-
  # anchored absolute paths in project-config.yaml then leaked into commits
  # because `.gaia/config/` was not ignored, contradicting the header comment
  # the config file itself emits. The marker-only idempotency check above
  # would otherwise leave that older block in place untouched. Append the
  # missing entries (each guarded by an exact-line `grep -Fxq`) so a re-run
  # of /gaia-init back-fills the gap without rewriting the whole block.
  # AF-2026-06-02-1 / Test16 F-L04 — the pytest ignores are also
  # back-filled on the marker-only idempotency path so an older
  # gaia-init that pre-dates the F-L04 fix back-fills the gap.
  for _line in '.gaia/config/' '.gaia/memory/' '.gaia/state/' '.coverage' '.coverage.*' '.pytest_cache/' '__pycache__/' '*.py[cod]'; do
    if ! grep -Fxq "$_line" "$gitignore_path"; then
      printf '%s\n' "$_line" >> "$gitignore_path"
      printf '%s: back-filled %s entry in %s\n' "$SCRIPT_NAME" "$_line" "$gitignore_path" >&2
    fi
  done
fi

exit 0
