#!/usr/bin/env bash
# generate-ci-scaffold.sh — write a starter CI workflow + a never-clobbered
# *.user-steps.yml companion for the requested provider. Deterministic output.
#
# Provider → canonical path map:
#   github-actions       → .github/workflows/gaia-pre-merge.yml
#   gitlab-ci            → .gitlab-ci.yml
#   circleci             → .circleci/config.yml
#   jenkins              → Jenkinsfile
#   azure-pipelines      → azure-pipelines.yml
#   bitbucket-pipelines  → bitbucket-pipelines.yml
#   none                 → no-op (exit 0, write nothing)
#
# Each provider produces a workflow file (regenerated on every run, header:
# `# Generated by /gaia-init`) and a companion `<workflow>.user-steps.yml`
# that is preserved byte-for-byte if it already exists. For
# providers without a YAML extension (Jenkinsfile), the companion takes the
# form `<filename>.user-steps.yml`.
#
# Usage:
#   generate-ci-scaffold.sh --path <project-root> --provider <provider>
#
# Exit codes:
#   0  Files written (or no-op for provider=none).
#   1  Unknown provider.
#   2  Usage error.

set -euo pipefail
LC_ALL=C
export LC_ALL

SCRIPT_NAME="gaia-init/generate-ci-scaffold.sh"

target=""
provider=""

while [ $# -gt 0 ]; do
  case "$1" in
    --path)
      [ $# -ge 2 ] || { printf '%s: --path requires a value\n' "$SCRIPT_NAME" >&2; exit 2; }
      target="$2"; shift 2 ;;
    --provider)
      [ $# -ge 2 ] || { printf '%s: --provider requires a value\n' "$SCRIPT_NAME" >&2; exit 2; }
      provider="$2"; shift 2 ;;
    --help|-h) sed -n '1,30p' "$0"; exit 0 ;;
    *) printf '%s: unexpected argument: %s\n' "$SCRIPT_NAME" "$1" >&2; exit 2 ;;
  esac
done

[ -n "$target" ]   || { printf '%s: --path is required\n' "$SCRIPT_NAME" >&2; exit 2; }
[ -n "$provider" ] || { printf '%s: --provider is required\n' "$SCRIPT_NAME" >&2; exit 2; }

case "$provider" in
  none) exit 0 ;;
  github-actions|gitlab-ci|circleci|jenkins|azure-pipelines|bitbucket-pipelines) ;;
  *)
    printf '%s: unknown provider: %s\n' "$SCRIPT_NAME" "$provider" >&2
    printf '%s: supported: github-actions, gitlab-ci, circleci, jenkins, azure-pipelines, bitbucket-pipelines, none\n' "$SCRIPT_NAME" >&2
    exit 1
    ;;
esac

# Resolve path + companion path per provider.
case "$provider" in
  github-actions)
    workflow="$target/.github/workflows/gaia-pre-merge.yml"
    companion="$target/.github/workflows/gaia-pre-merge.user-steps.yml"
    ;;
  gitlab-ci)
    workflow="$target/.gitlab-ci.yml"
    companion="$target/.gitlab-ci.user-steps.yml"
    ;;
  circleci)
    workflow="$target/.circleci/config.yml"
    companion="$target/.circleci/config.user-steps.yml"
    ;;
  jenkins)
    workflow="$target/Jenkinsfile"
    companion="$target/Jenkinsfile.user-steps.yml"
    ;;
  azure-pipelines)
    workflow="$target/azure-pipelines.yml"
    companion="$target/azure-pipelines.user-steps.yml"
    ;;
  bitbucket-pipelines)
    workflow="$target/bitbucket-pipelines.yml"
    companion="$target/bitbucket-pipelines.user-steps.yml"
    ;;
esac

mkdir -p -- "$(dirname "$workflow")"

# --- workflow file (always regenerated) -------------------------------------
write_workflow() {
  case "$provider" in
    github-actions)
      cat > "$workflow" <<'YAML'
# Generated by /gaia-init
# Starter GAIA pre-merge pipeline. Customize free-form additions in the
# companion *.user-steps.yml file — that companion survives regeneration.
name: gaia-pre-merge
on:
  pull_request:
    branches: [main, staging]
jobs:
  gaia-gates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run GAIA pre-merge gates
        run: echo "GAIA pre-merge gate is not yet configured for this project. Run /gaia-ci-setup to wire the runner, then commit the generated workflow. See plugins/gaia/skills/gaia-init/docs/ci-scaffold-stub.html for the rationale." >&2 && exit 1
YAML
      ;;
    gitlab-ci)
      cat > "$workflow" <<'YAML'
# Generated by /gaia-init
# Starter GAIA pre-merge pipeline. Customize via .gitlab-ci.user-steps.yml.
stages:
  - gaia-gates
gaia-pre-merge:
  stage: gaia-gates
  script:
    - echo "GAIA pre-merge gate is not yet configured for this project. Run /gaia-ci-setup to wire the runner, then commit the generated workflow. See plugins/gaia/skills/gaia-init/docs/ci-scaffold-stub.html for the rationale." >&2 && exit 1
YAML
      ;;
    circleci)
      cat > "$workflow" <<'YAML'
# Generated by /gaia-init
# Starter GAIA pre-merge pipeline. Customize via .circleci/config.user-steps.yml.
version: 2.1
jobs:
  gaia-pre-merge:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "GAIA pre-merge gate is not yet configured for this project. Run /gaia-ci-setup to wire the runner, then commit the generated workflow. See plugins/gaia/skills/gaia-init/docs/ci-scaffold-stub.html for the rationale." >&2 && exit 1
workflows:
  default:
    jobs: [gaia-pre-merge]
YAML
      ;;
    jenkins)
      cat > "$workflow" <<'GROOVY'
// Generated by /gaia-init
// Starter GAIA pre-merge pipeline. Customize via Jenkinsfile.user-steps.yml.
pipeline {
  agent any
  stages {
    stage('GAIA Pre-Merge') {
      steps {
        sh 'echo "GAIA pre-merge gate is not yet configured for this project. Run /gaia-ci-setup to wire the runner, then commit the generated workflow. See plugins/gaia/skills/gaia-init/docs/ci-scaffold-stub.html for the rationale." >&2 && exit 1'
      }
    }
  }
}
GROOVY
      ;;
    azure-pipelines)
      cat > "$workflow" <<'YAML'
# Generated by /gaia-init
# Starter GAIA pre-merge pipeline. Customize via azure-pipelines.user-steps.yml.
trigger:
  branches:
    include: [main, staging]
pool:
  vmImage: 'ubuntu-latest'
steps:
  - script: echo "GAIA pre-merge gate is not yet configured for this project. Run /gaia-ci-setup to wire the runner, then commit the generated workflow. See plugins/gaia/skills/gaia-init/docs/ci-scaffold-stub.html for the rationale." >&2 && exit 1
    displayName: GAIA pre-merge gates
YAML
      ;;
    bitbucket-pipelines)
      cat > "$workflow" <<'YAML'
# Generated by /gaia-init
# Starter GAIA pre-merge pipeline. Customize via bitbucket-pipelines.user-steps.yml.
pipelines:
  pull-requests:
    '**':
      - step:
          name: GAIA pre-merge gates
          script:
            - echo "GAIA pre-merge gate is not yet configured for this project. Run /gaia-ci-setup to wire the runner, then commit the generated workflow. See plugins/gaia/skills/gaia-init/docs/ci-scaffold-stub.html for the rationale." >&2 && exit 1
YAML
      ;;
  esac
}

write_workflow

# --- companion file (NEVER overwritten) -------------------------------------
if [ ! -e "$companion" ]; then
  cat > "$companion" <<'YAML'
# *.user-steps.yml — user-customized pipeline additions.
# This file is created once by /gaia-init and is NEVER overwritten by
# /gaia-init or /gaia-config-ci-regenerate. Add free-form steps below.
steps: []
YAML
fi

exit 0
