#!/usr/bin/env bash
# generate-config.sh — convert a JSON answer-bundle (stdin) into a complete
# config/project-config.yaml at the target project root.
# Story: E71-S1 (FR-RSV2-34, AC2). Deterministic per ADR-042.
#
# Atomic write: serialize to <target>.tmp first, then rename. Refuses to
# clobber an existing config (greenfield invariant — AC4).
#
# Input JSON shape (all keys optional unless noted):
#   {
#     "project_shape": "single backend|microservices|mobile only|mobile+backend|microservices+mobile",
#     "stacks": [{"name": "...", "language": "...", "paths": ["..."]}, ...],
#     "compliance": {"regimes": ["gdpr", ...], "ui_present": true},
#     "environments": {"<env>": {"url": "...", "credentials": {"<key>": "<ENV_VAR_NAME>"}}, ...},
#     "ci_platform": {"provider": "github-actions|none|...", "pipeline": "..."},
#     "platforms": ["ios"|"android"|"web", ...],
#     "device_targets": {"ios": ["iPhone 15"], ...}
#   }
#
# Usage:
#   generate-config.sh --path <project-root> --name <project-name> < answers.json
#
# Exit codes:
#   0  Wrote config/project-config.yaml.
#   1  Refused to clobber existing config (greenfield invariant).
#   2  Usage error / malformed input.

set -euo pipefail
LC_ALL=C
export LC_ALL

SCRIPT_NAME="gaia-init/generate-config.sh"

target=""
name=""

while [ $# -gt 0 ]; do
  case "$1" in
    --path)
      [ $# -ge 2 ] || { printf '%s: --path requires a value\n' "$SCRIPT_NAME" >&2; exit 2; }
      target="$2"; shift 2 ;;
    --name)
      [ $# -ge 2 ] || { printf '%s: --name requires a value\n' "$SCRIPT_NAME" >&2; exit 2; }
      name="$2"; shift 2 ;;
    --help|-h) sed -n '1,30p' "$0"; exit 0 ;;
    *) printf '%s: unexpected argument: %s\n' "$SCRIPT_NAME" "$1" >&2; exit 2 ;;
  esac
done

[ -n "$target" ] || { printf '%s: --path is required\n' "$SCRIPT_NAME" >&2; exit 2; }
[ -n "$name" ]   || { printf '%s: --name is required\n' "$SCRIPT_NAME" >&2; exit 2; }

mkdir -p -- "$target/config"

cfg_path="$target/config/project-config.yaml"
if [ -e "$cfg_path" ]; then
  printf '%s: refuses to overwrite existing config: %s\n' "$SCRIPT_NAME" "$cfg_path" >&2
  exit 1
fi

# Read stdin into a temp file so we can parse it with whichever tool is available.
in_json="$(mktemp -t gaia-init-answers.XXXXXX)"
trap 'rm -f -- "$in_json" 2>/dev/null || true' EXIT
cat > "$in_json"

# Resolve absolute path for project_root (POSIX-portable; falls back to as-is).
abs_target="$target"
if [ -d "$target" ]; then
  abs_target="$(cd "$target" && pwd)"
fi

# We deliberately avoid jq dependence — many GAIA installs are bare. A
# minimal Python fallback is used (Python 3 is available on every supported
# OS); if Python is also missing we fall back to a literal echo of stdin.
yaml_path="$cfg_path.tmp"

emit_yaml() {
  if command -v python3 >/dev/null 2>&1; then
    python3 - "$abs_target" "$name" "$in_json" "$yaml_path" <<'PYEOF'
import json, sys, os, datetime

abs_target, name, in_json, out_path = sys.argv[1:5]
with open(in_json) as f:
    data = json.load(f) if os.path.getsize(in_json) > 0 else {}

today = datetime.datetime.utcnow().strftime("%Y-%m-%d")

def yaml_quote(s):
    s = str(s)
    if s == "" or any(c in s for c in ":#&*!|>'\"%@`{}[],"):
        return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'
    return s

lines = []
lines.append("# project-config.yaml — generated by /gaia-init")
lines.append(f"# Project: {name}")
lines.append("")
lines.append(f"project_root: {abs_target}")
lines.append(f"project_path: {abs_target}")
lines.append(f"memory_path: {abs_target}/_memory")
lines.append(f"checkpoint_path: {abs_target}/_memory/checkpoints")
lines.append(f"installed_path: {abs_target}")
lines.append("framework_version: 0.0.0")
lines.append(f"date: {today}")

stacks = data.get("stacks") or []
if stacks:
    lines.append("")
    lines.append("stacks:")
    for s in stacks:
        lines.append(f"  - name: {yaml_quote(s.get('name', ''))}")
        lines.append(f"    language: {yaml_quote(s.get('language', ''))}")
        lines.append("    paths:")
        for p in s.get("paths", []) or []:
            lines.append(f"      - {yaml_quote(p)}")

compliance = data.get("compliance") or {}
if compliance:
    lines.append("")
    lines.append("compliance:")
    regimes = compliance.get("regimes") or []
    if regimes:
        lines.append("  regimes:")
        for r in regimes:
            lines.append(f"    - {yaml_quote(r)}")
    if "ui_present" in compliance:
        lines.append(f"  ui_present: {'true' if compliance['ui_present'] else 'false'}")
    if compliance.get("domain"):
        lines.append(f"  domain: {yaml_quote(compliance['domain'])}")

envs = data.get("environments") or {}
if envs:
    lines.append("")
    lines.append("environments:")
    for env_name, env_body in envs.items():
        lines.append(f"  {yaml_quote(env_name)}:")
        if "url" in env_body:
            lines.append(f"    url: {yaml_quote(env_body['url'])}")
        creds = env_body.get("credentials") or {}
        if creds:
            lines.append("    credentials:")
            for k, v in creds.items():
                # v MUST be the env-var NAME, never a literal credential.
                lines.append(f"      {yaml_quote(k)}: {yaml_quote(v)}")

ci = data.get("ci_platform") or {}
if ci.get("provider"):
    lines.append("")
    lines.append("ci_platform:")
    lines.append(f"  provider: {yaml_quote(ci['provider'])}")
    if ci.get("pipeline"):
        lines.append(f"  pipeline: {yaml_quote(ci['pipeline'])}")

platforms = data.get("platforms") or []
if platforms:
    lines.append("")
    lines.append("platforms:")
    for p in platforms:
        lines.append(f"  - {yaml_quote(p)}")

device_targets = data.get("device_targets") or {}
if device_targets:
    lines.append("")
    lines.append("device_targets:")
    for plat, body in device_targets.items():
        lines.append(f"  {yaml_quote(plat)}:")
        # Two shapes accepted:
        #   1. Canonical (E74-S11): dict with os_versions / form_factors /
        #      screen_sizes per ADR-081 / project-config.schema.json.
        #   2. Legacy (E71-S1): list of device-name strings.
        if isinstance(body, dict):
            ov = body.get("os_versions") or []
            ff = body.get("form_factors") or []
            ss = body.get("screen_sizes") or []
            if ov:
                lines.append("    os_versions:")
                for v in ov:
                    # os_versions are schema-required strings; force quoting so
                    # values like "16.0" do not round-trip as YAML floats.
                    s = str(v).replace('\\', '\\\\').replace('"', '\\"')
                    lines.append(f'      - "{s}"')
            if ff:
                lines.append("    form_factors:")
                for v in ff:
                    lines.append(f"      - {yaml_quote(v)}")
            if ss:
                lines.append("    screen_sizes:")
                for s in ss:
                    if isinstance(s, dict):
                        lines.append(
                            f"      - {{ width: {int(s['width'])}, "
                            f"height: {int(s['height'])}, "
                            f"density: {s['density']} }}"
                        )
                    else:
                        # Pass-through string (rare).
                        lines.append(f"      - {yaml_quote(s)}")
        else:
            # Legacy list-of-strings shape.
            for d in body or []:
                lines.append(f"    - {yaml_quote(d)}")

with open(out_path, "w") as f:
    f.write("\n".join(lines) + "\n")
PYEOF
  else
    # Python 3 unavailable — emit a minimal valid config. The rich path is
    # the supported path; this fallback exists only so the script does not
    # hard-fail on stripped-down environments.
    cat > "$yaml_path" <<EOF
# project-config.yaml — generated by /gaia-init (minimal fallback)
# Project: $name

project_root: $abs_target
project_path: $abs_target
memory_path: $abs_target/_memory
checkpoint_path: $abs_target/_memory/checkpoints
installed_path: $abs_target
framework_version: 0.0.0
date: $(date -u +"%Y-%m-%d")
EOF
  fi
}

emit_yaml
mv -f -- "$yaml_path" "$cfg_path"
exit 0
