#!/usr/bin/env bash
# generate-readiness-report.sh — AF-2026-05-31-3 / Test14 F-21
#
# Deterministic readiness-report.md emitter for /gaia-readiness-check.
# Reads the two mandatory ADR-042 gates (traceability + ci-setup) plus
# the optional artifact presence inventory, and writes a minimal
# `readiness-report.md` to the canonical planning-artifacts location.
#
# The prior implementation had /gaia-readiness-check write the gate
# outcomes to a checkpoint + lifecycle event but produced NO artifact
# file — the SKILL.md documented the report at line 186 but no script
# materialised it, so headless YOLO runs left the report missing and
# the audit harness recorded a false-positive "no artifact found".
#
# This script makes the LLM authoring path optional: it lays down a
# canonical-shape stub that the orchestrating LLM can later enrich
# without losing the at-rest record of the gate result. Idempotent —
# refuses to overwrite an existing non-stub report.
#
# Usage:
#   generate-readiness-report.sh --status <PASS|FAIL> --project-root <dir>
#
# Exit codes:
#   0  report written (or no-op when already present and non-stub)
#   2  argument error

set -euo pipefail
LC_ALL=C
export LC_ALL

SCRIPT_NAME="gaia-readiness-check/generate-readiness-report.sh"
log()  { printf 'INFO: %s: %s\n' "$SCRIPT_NAME" "$*" >&2; }
die()  { printf 'ERROR: %s: %s\n' "$SCRIPT_NAME" "$*" >&2; exit 2; }

STATUS=""
PROJECT_ROOT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --status)       STATUS="${2:-}"; shift 2 ;;
    --project-root) PROJECT_ROOT="${2:-}"; shift 2 ;;
    -h|--help)
      cat <<EOF
$SCRIPT_NAME — readiness-report.md generator (AF-2026-05-31-3 / Test14 F-21)

Usage:
  $0 --status <PASS|FAIL> --project-root <dir>

Writes a canonical-shape readiness-report.md to
<project-root>/.gaia/artifacts/planning-artifacts/readiness-report.md.
Idempotent — refuses to overwrite an existing non-stub report.
EOF
      exit 0 ;;
    *) die "unknown flag: $1" ;;
  esac
done

[ -n "$STATUS" ]       || die "--status required (PASS|FAIL)"
[ -n "$PROJECT_ROOT" ] || die "--project-root required"
[ -d "$PROJECT_ROOT" ] || die "project root does not exist: $PROJECT_ROOT"

case "$STATUS" in
  PASS|FAIL) : ;;
  *) die "--status must be PASS or FAIL (got: $STATUS)" ;;
esac

OUT_DIR="$PROJECT_ROOT/.gaia/artifacts/planning-artifacts"
OUT_FILE="$OUT_DIR/readiness-report.md"
mkdir -p "$OUT_DIR"

# Refuse to overwrite a non-stub report (operators / LLM may have enriched it).
if [ -f "$OUT_FILE" ] && ! grep -qF 'AF-2026-05-31-3 / Test14 F-21' "$OUT_FILE" 2>/dev/null; then
  log "$OUT_FILE already exists and is not a stub — refusing to overwrite (delete it to regenerate)"
  exit 0
fi

_now_iso="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Probe the two ADR-042 mandatory gates so the report's body reflects
# concrete on-disk state at the moment of write.
_trace_path="$PROJECT_ROOT/.gaia/artifacts/planning-artifacts/traceability-matrix.md"
_ci_path="$PROJECT_ROOT/.gaia/artifacts/test-artifacts/ci-setup.md"
_trace_status="MISSING"
_ci_status="MISSING"
[ -f "$_trace_path" ] && [ -s "$_trace_path" ] && _trace_status="PRESENT"
[ -f "$_ci_path" ]    && [ -s "$_ci_path" ]    && _ci_status="PRESENT"

cat > "$OUT_FILE" <<EOF
---
artifact_type: readiness-report
generated_by: /gaia-readiness-check
generated_at: "$_now_iso"
status: $STATUS
schema_version: "2.0.0"
# AF-2026-05-31-3 / Test14 F-21: stub canonical-shape report emitted by
# generate-readiness-report.sh. The LLM authoring path documented in the
# /gaia-readiness-check SKILL.md Step 9 may overwrite this file with a
# richer report; the script's check guards against blowing away that
# enrichment on re-run.
---

# Readiness Report

**Status:** \`$STATUS\` — generated $_now_iso

## Mandatory gates (ADR-042)

| Gate | Status |
| ---- | ------ |
| Traceability matrix (\`traceability-matrix.md\`) | $_trace_status |
| CI setup (\`ci-setup.md\`) | $_ci_status |

## Notes

- This report is the at-rest record of the readiness check's gate
  outcomes. The orchestrating LLM may enrich the body with project-
  specific narrative; the YAML frontmatter \`status\` field is the
  authoritative machine-readable signal.
- Generated by \`${SCRIPT_NAME}\` per Test14 F-21. Delete this file to
  force a fresh stub on the next \`/gaia-readiness-check\` invocation.
EOF

log "wrote $OUT_FILE (status=$STATUS, traceability=$_trace_status, ci_setup=$_ci_status)"
exit 0
