#!/usr/bin/env bash
# ci-regen-header.sh — header emit/parse/hash helper for /gaia-config-ci --regenerate.
#
# Subcommands:
#   emit <hash>   Emit the four-line YAML-comment header on stdout.
#                   1. Attribution line referencing /gaia-config-ci.
#                   2. DO NOT EDIT warning referencing --regenerate.
#                   3. Source hash line: "# Source hash: sha256:<hash>"
#                   4. Generated-at ISO-8601 UTC timestamp.
#   hash          Read stdin, emit lowercase sha256 hex on stdout. Used for
#                 hashing CI-relevant config sections AND generated-file bodies.
#   parse <file>  Extract the Source hash from the file's header. Exits 2 if
#                 the file has no Source-hash line.
#

set -euo pipefail
LC_ALL=C
export LC_ALL

cmd="${1:-}"
shift || true

emit_header() {
  local hash="${1:-}"
  if [ -z "$hash" ]; then
    echo "ci-regen-header.sh emit: missing hash argument" >&2
    exit 64
  fi
  local ts
  ts="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  printf '# Generated by /gaia-config-ci from project-config.yaml\n'
  printf '# DO NOT EDIT this file by hand — run `/gaia-config-ci --regenerate` to refresh.\n'
  printf '# Source hash: sha256:%s\n' "$hash"
  printf '# Generated at: %s\n' "$ts"
}

hash_stream() {
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 | cut -d' ' -f1
  elif command -v sha256sum >/dev/null 2>&1; then
    sha256sum | cut -d' ' -f1
  else
    echo "ci-regen-header.sh: no sha256 tool available (need shasum or sha256sum)" >&2
    exit 65
  fi
}

parse_header() {
  local file="${1:-}"
  if [ -z "$file" ] || [ ! -f "$file" ]; then
    echo "ci-regen-header.sh parse: file not found: $file" >&2
    exit 2
  fi
  local hash_line
  hash_line="$(grep -E '^# Source hash: sha256:[0-9a-f]+$' "$file" | head -1 || true)"
  if [ -z "$hash_line" ]; then
    exit 2
  fi
  printf '%s\n' "${hash_line#*sha256:}"
}

case "$cmd" in
  emit)  emit_header "$@" ;;
  hash)  hash_stream ;;
  parse) parse_header "$@" ;;
  ""|-h|--help)
    sed -n '1,20p' "$0"
    ;;
  *)
    echo "ci-regen-header.sh: unknown subcommand: $cmd" >&2
    exit 64
    ;;
esac
