#!/usr/bin/env bats
# test-automate-subcommands.bats — E72-S2 sub-command tests
#
# Validates:
#   AC1/AC2: --status sub-command emits a coverage map + summary line, plus
#            a Custom scenarios block when CS-NNN entries exist.
#   AC3/AC4: --add-scenario sub-command allocates next CS-NNN, writes to
#            both the story TC list and custom/test-scenarios/index.yaml.
#   AC5/AC6: --scaffold sub-command generates placeholder skeletons, does
#            NOT update the Review Gate as PASSED, and the output is
#            detected as low_quality_test_generated by the deterministic
#            placeholder gate.
#   AC7:     SKILL.md documents each sub-command's usage / argument syntax
#            / output format.
#
# Refs: E72-S2, FR-RSV2-40, source-report §5.8 / §11.1 / §11.2
#
# Usage:
#   bats gaia-public/tests/cluster-9-parity/test-automate-subcommands.bats
#
# Dependencies: bats-core 1.10+

setup() {
  REPO_ROOT="$(cd "$BATS_TEST_DIRNAME/../.." && pwd)"
  PROJECT_ROOT="$(cd "$REPO_ROOT/.." && pwd)"
  SKILL_DIR="$REPO_ROOT/plugins/gaia/skills/gaia-test-automate"
  SCRIPTS_DIR="$SKILL_DIR/scripts"
  REVIEW_COMMON_DIR="$REPO_ROOT/plugins/gaia/scripts/review-common"
  CUSTOM_DIR="$PROJECT_ROOT/custom/test-scenarios"

  TMPDIR="$(mktemp -d -t e72s2.XXXXXX)"
  STORY_DIR="$TMPDIR/docs/implementation-artifacts"
  mkdir -p "$STORY_DIR"

  STORY_FILE="$STORY_DIR/E99-S99-fixture-story.md"
  cat >"$STORY_FILE" <<'EOF'
---
key: "E99-S99"
title: "Fixture Story"
status: in-progress
---

# Story: Fixture

## Acceptance Criteria

- [ ] AC1: First criterion
- [ ] AC2: Second criterion
- [ ] AC3: Third criterion

## Test Cases

| TC | AC | Tier | File |
|----|----|------|------|
| TC-001 | AC1 | unit | tests/unit/foo.test.ts |
| TC-002 | AC2 | integration | tests/int/bar.spec.ts |

## Custom Scenarios

| CS | Tier | Description | File |
|----|------|-------------|------|

## Review Gate

| Review | Status | Report |
|--------|--------|--------|
| Code Review | UNVERIFIED | — |
| QA Tests | UNVERIFIED | — |
| Security Review | UNVERIFIED | — |
| Test Automation | UNVERIFIED | — |
| Test Review | UNVERIFIED | — |
| Performance Review | UNVERIFIED | — |
EOF
}

teardown() {
  rm -rf "$TMPDIR"
}

# ---------- AC1 / AC2: --status ----------

@test "E72-S2 AC1: subcmd-status.sh exists and is executable" {
  [ -x "$SCRIPTS_DIR/subcmd-status.sh" ]
}

@test "E72-S2 AC1: --status emits AC/TC/tier/file coverage rows" {
  run "$SCRIPTS_DIR/subcmd-status.sh" --story-file "$STORY_FILE"
  [ "$status" -eq 0 ]
  echo "$output" | grep -qE 'AC1[[:space:]]+TC-001[[:space:]]+unit'
  echo "$output" | grep -qE 'AC2[[:space:]]+TC-002[[:space:]]+integration'
  echo "$output" | grep -qE 'AC3[[:space:]]+\(not yet automated\)|AC3[[:space:]]+(-|—)[[:space:]]+(-|—)'
}

@test "E72-S2 AC1: --status emits summary line with generated/total" {
  run "$SCRIPTS_DIR/subcmd-status.sh" --story-file "$STORY_FILE"
  [ "$status" -eq 0 ]
  echo "$output" | grep -qE '2/3 generated.*1 pending'
}

@test "E72-S2 AC2: --status renders Custom scenarios block when CS entries exist" {
  # Append a CS-001 entry to the story
  awk 'BEGIN{p=0} /^\| CS \| Tier \| Description \| File \|$/{print;p=1;next} /^\|----\|------\|-------------\|------\|$/ && p==1{print;print "| CS-001 | unit | edge case for retry | tests/unit/cs-001.test.ts |";p=2;next}{print}' "$STORY_FILE" > "$STORY_FILE.new"
  mv "$STORY_FILE.new" "$STORY_FILE"

  run "$SCRIPTS_DIR/subcmd-status.sh" --story-file "$STORY_FILE"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q 'Custom scenarios'
  echo "$output" | grep -q 'CS-001'
  echo "$output" | grep -q 'tests/unit/cs-001.test.ts'
}

# ---------- AC3 / AC4: --add-scenario ----------

@test "E72-S2 AC3: subcmd-add-scenario.sh exists and is executable" {
  [ -x "$SCRIPTS_DIR/subcmd-add-scenario.sh" ]
}

@test "E72-S2 AC3: --add-scenario allocates next CS-NNN" {
  INDEX="$TMPDIR/custom/test-scenarios/index.yaml"
  mkdir -p "$(dirname "$INDEX")"
  cat >"$INDEX" <<'EOF'
scenarios:
  - story_key: E99-S99
    cs_id: CS-001
    description: "preexisting"
    tier: unit
    file_path: ""
  - story_key: E99-S99
    cs_id: CS-002
    description: "another preexisting"
    tier: integration
    file_path: ""
EOF

  run "$SCRIPTS_DIR/subcmd-add-scenario.sh" \
    --story-file "$STORY_FILE" \
    --index-file "$INDEX" \
    --description "race condition on retry" \
    --tier unit \
    --priority P1 \
    --expected "deduped retry"
  [ "$status" -eq 0 ]
  echo "$output" | grep -qE 'CS-003'
}

@test "E72-S2 AC4: --add-scenario writes entry to index.yaml" {
  INDEX="$TMPDIR/custom/test-scenarios/index.yaml"
  mkdir -p "$(dirname "$INDEX")"
  printf 'scenarios: []\n' >"$INDEX"

  run "$SCRIPTS_DIR/subcmd-add-scenario.sh" \
    --story-file "$STORY_FILE" \
    --index-file "$INDEX" \
    --description "boundary input" \
    --tier integration \
    --priority P2 \
    --expected "graceful reject"
  [ "$status" -eq 0 ]

  # Verify index.yaml has the new CS entry
  grep -q 'cs_id: CS-001' "$INDEX"
  grep -q 'story_key: E99-S99' "$INDEX"
  grep -q 'description: "boundary input"' "$INDEX"
  grep -q 'tier: integration' "$INDEX"
  grep -q 'file_path: ""' "$INDEX"
}

@test "E72-S2 AC4: --add-scenario appends row to story Custom Scenarios table" {
  INDEX="$TMPDIR/custom/test-scenarios/index.yaml"
  mkdir -p "$(dirname "$INDEX")"
  printf 'scenarios: []\n' >"$INDEX"

  run "$SCRIPTS_DIR/subcmd-add-scenario.sh" \
    --story-file "$STORY_FILE" \
    --index-file "$INDEX" \
    --description "audit trail check" \
    --tier unit \
    --priority P1 \
    --expected "row written"
  [ "$status" -eq 0 ]

  # Story file now contains CS-001 row in the Custom Scenarios table
  grep -q '| CS-001 |' "$STORY_FILE"
  grep -q 'audit trail check' "$STORY_FILE"
}

# ---------- AC5 / AC6: --scaffold ----------

@test "E72-S2 AC5: subcmd-scaffold.sh exists and is executable" {
  [ -x "$SCRIPTS_DIR/subcmd-scaffold.sh" ]
}

@test "E72-S2 AC5: --scaffold generates skeletons for unmapped ACs and skips Review Gate write" {
  OUTDIR="$TMPDIR/scaffold-out"
  mkdir -p "$OUTDIR"
  run "$SCRIPTS_DIR/subcmd-scaffold.sh" \
    --story-file "$STORY_FILE" \
    --out-dir "$OUTDIR" \
    --stack ts-dev
  [ "$status" -eq 0 ]
  # AC3 was unmapped — skeleton generated for it
  ls "$OUTDIR" | grep -qE 'AC3'
  # Hard invariant: stderr or stdout MUST contain explicit "review gate not updated"
  echo "$output" | grep -qiE 'review gate.*(not|skip)'
}

@test "E72-S2 AC6: scaffold output triggers placeholder-test-detector low_quality_test_generated" {
  OUTDIR="$TMPDIR/scaffold-out"
  mkdir -p "$OUTDIR"
  "$SCRIPTS_DIR/subcmd-scaffold.sh" \
    --story-file "$STORY_FILE" \
    --out-dir "$OUTDIR" \
    --stack ts-dev >/dev/null

  run "$REVIEW_COMMON_DIR/placeholder-test-detector.sh" --dir "$OUTDIR"
  # Detector exits 1 when placeholders are found
  [ "$status" -eq 1 ]
  echo "$output" | grep -q 'low_quality_test_generated'
}

# ---------- AC7: SKILL.md documentation ----------

@test "E72-S2 AC7: SKILL.md documents --status sub-command" {
  grep -q '\-\-status' "$SKILL_DIR/SKILL.md"
  # Documentation block: usage + output format
  grep -qE 'usage:.*--status|--status.*Coverage map' "$SKILL_DIR/SKILL.md"
}

@test "E72-S2 AC7: SKILL.md documents --add-scenario sub-command" {
  grep -q '\-\-add-scenario' "$SKILL_DIR/SKILL.md"
  grep -qE 'usage:.*--add-scenario|--add-scenario.*CS-NNN' "$SKILL_DIR/SKILL.md"
}

@test "E72-S2 AC7: SKILL.md documents --scaffold sub-command" {
  grep -q '\-\-scaffold' "$SKILL_DIR/SKILL.md"
  grep -qiE 'usage:.*--scaffold|--scaffold.*(skeleton|review gate)' "$SKILL_DIR/SKILL.md"
}

@test "E72-S2 AC7: SKILL.md has explicit Sub-command Routing section" {
  grep -qE '^##? +Sub-?command|^##? +Sub-Command Routing' "$SKILL_DIR/SKILL.md"
}
