#!/usr/bin/env bash
# generate-pipeline.sh — deterministic CI workflow generator for /gaia-ci-setup
#
# Deterministic CI workflow generator for /gaia-ci-setup Step 8. Replaces
# the prior LLM-only authoring path so a headless YOLO `/gaia-ci-setup`
# invocation can actually produce a runnable workflow file (rather than
# leaving the exit-1 stub init's `generate-ci-scaffold.sh` emits).
#
# Reads the active test-environment.yaml + project-config.yaml to learn
# which stack the project uses, then emits a stack-aware GitHub Actions
# `gaia-pre-merge.yml` whose pre-merge gates ACTUALLY RUN something
# instead of `exit 1`.
#
# Multi-stack mode: when --config points to a project config with two or
# more stacks[], the generator produces:
#   1. selective-tests.yml — affected-set narrowing + promotion full-suite
#   2. gaia-release.yml — per-component release workflow
#   3. Vendored engine scripts under .gaia/ci-scripts/ with drift manifest
# Single-stack mode is preserved (gaia-pre-merge.yml only, no regression).
#
# Currently supports: github-actions on python/node/go/jvm. Other providers
# (gitlab-ci/circleci/jenkins/azure-pipelines/bitbucket-pipelines) fall
# through with a clear message naming the supported set + pointing the
# operator at the init-generated stub for hand-editing.
#
# Usage:
#   generate-pipeline.sh --provider <ci> --stack <stack> --project-root <dir>
#   generate-pipeline.sh --provider <ci> --config <config> --project-root <dir>
#
# Exit codes:
#   0  workflow written (or no-op when already correct)
#   1  unsupported provider / missing inputs
#   2  argument error

set -euo pipefail
LC_ALL=C
export LC_ALL

_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Root-level scripts directory (the existing engine scripts)
_ENGINE_SCRIPTS_DIR="$(cd "$_SCRIPT_DIR/../../../scripts" && pwd)"

SCRIPT_NAME="gaia-ci-setup/generate-pipeline.sh"
_log()  { printf 'INFO: %s: %s\n' "$SCRIPT_NAME" "$*" >&2; }
_warn() { printf 'WARNING: %s: %s\n' "$SCRIPT_NAME" "$*" >&2; }
_die()  { printf 'ERROR: %s: %s\n' "$SCRIPT_NAME" "$*" >&2; exit "${2:-2}"; }

# ---------------------------------------------------------------------------
# count_config_stacks CONFIG — count stacks[] entries in a project config.
# Output: integer count on stdout.
# ---------------------------------------------------------------------------
count_config_stacks() {
  local config="$1"
  awk '
  BEGIN { in_stacks = 0; count = 0 }
  /^stacks:/ { in_stacks = 1; next }
  in_stacks && /^[a-zA-Z_]/ { in_stacks = 0; next }
  in_stacks && /^[[:space:]]+-[[:space:]]+name:/ { count++ }
  END { print count }
  ' "$config"
}

# ---------------------------------------------------------------------------
# _read_stack_names CONFIG — read stack names from config, one per line
# ---------------------------------------------------------------------------
_read_stack_names() {
  local config="$1"
  awk '
  BEGIN { in_stacks = 0 }
  /^stacks:/ { in_stacks = 1; next }
  in_stacks && /^[a-zA-Z_]/ { in_stacks = 0; next }
  in_stacks && /^[[:space:]]+-[[:space:]]+name:/ {
    val = $0
    sub(/.*name:[[:space:]]*/, "", val)
    gsub(/^[[:space:]]+/, "", val)
    gsub(/[[:space:]]+$/, "", val)
    gsub(/^"/, "", val); gsub(/"$/, "", val)
    if (val != "") print val
  }
  ' "$config"
}

# ---------------------------------------------------------------------------
# _read_final_branch CONFIG — read the last promotion_chain[].branch value
# ---------------------------------------------------------------------------
_read_final_branch() {
  local config="$1"
  awk '
  BEGIN { in_chain = 0; branch = "" }
  /^[[:space:]]*promotion_chain:/ { in_chain = 1; next }
  in_chain && /^[a-zA-Z_]/ { in_chain = 0; next }
  in_chain && /^[[:space:]]+- id:/ { branch = "" }
  in_chain && /branch:/ {
    val = $0
    sub(/.*branch:[[:space:]]*/, "", val)
    gsub(/^[[:space:]]+/, "", val)
    gsub(/[[:space:]]+$/, "", val)
    gsub(/^"/, "", val); gsub(/"$/, "", val)
    if (val != "") branch = val
  }
  END { print (branch != "" ? branch : "main") }
  ' "$config"
}

# ---------------------------------------------------------------------------
# _generate_selective_tests CONFIG PROJECT_ROOT — emit selective-tests.yml
# Generates a config-driven selective-tests workflow that delegates to the
# existing engine scripts (selective-test-driver.sh, detect-affected.sh).
# ---------------------------------------------------------------------------
_generate_selective_tests() {
  local config="$1"
  local project_root="$2"
  local final_branch
  final_branch="$(_read_final_branch "$config")"

  local wf_dir="$project_root/.github/workflows"
  mkdir -p "$wf_dir"
  local wf="$wf_dir/selective-tests.yml"

  local _tmp
  _tmp="$(mktemp "${wf}.XXXXXX")"
  cat > "$_tmp" <<'SELECTIVE_EOF'
# Generated by /gaia-ci-setup — multi-stack selective-tests workflow.
# Affected-set narrowing on PRs, full-suite escalation on promotion merges.
# Engine: .gaia/ci-scripts/selective-test-driver.sh chains detect-affected,
# cross-refs-walk, reconcile-stale-graph, apply-test-policy, generate-pipeline.
#
# PR-only. The pull_request event covers both legs: feature->staging PRs get
# the affected-set narrowing, and the staging->main promotion PR triggers the
# full-suite escalation (the promotion step reads
# github.event.pull_request.base.ref == final tier). No push: trigger — the
# same matrix would re-run on the post-merge commit (pure duplication on a
# squash-merge flow).
name: selective-tests
on:
  pull_request:
    branches: [main, staging]
jobs:
  plan:
    name: plan
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.driver.outputs.matrix }}
      config_path: ${{ steps.cfg.outputs.config_path }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine trigger type
        id: trigger
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "type=pr" >> "$GITHUB_OUTPUT"
          else
            echo "type=push" >> "$GITHUB_OUTPUT"
          fi

      - name: Resolve project config
        id: cfg
        run: |
          rel=".gaia/config/project-config.yaml"
          ci_slice=".gaia/ci-config.yaml"
          config_path=""
          location=""

          if [[ -n "${GAIA_CONFIG:-}" && -f "${GAIA_CONFIG}" ]]; then
            config_path="${GAIA_CONFIG}"; location="env:GAIA_CONFIG"
          elif [[ -f "${ci_slice}" ]]; then
            config_path="${ci_slice}"; location="ci-slice"
          elif [[ -n "${CLAUDE_PROJECT_ROOT:-}" && -f "${CLAUDE_PROJECT_ROOT}/${rel}" ]]; then
            config_path="${CLAUDE_PROJECT_ROOT}/${rel}"; location="env:CLAUDE_PROJECT_ROOT"
          else
            dir="$PWD"
            while :; do
              if [[ -f "${dir}/${rel}" ]]; then
                config_path="${dir}/${rel}"
                [[ "$dir" == "$PWD" ]] && location="checkout-root" || location="parent:${dir}"
                break
              fi
              [[ "$dir" == "/" || -z "$dir" ]] && break
              dir="$(dirname -- "$dir")"
            done
          fi

          if [[ -n "$config_path" ]]; then
            echo "found=true" >> "$GITHUB_OUTPUT"
            echo "config_path=${config_path}" >> "$GITHUB_OUTPUT"
            if [[ "$location" == "checkout-root" || "$location" == "ci-slice" || "$location" == "env:GAIA_CONFIG" ]]; then
              echo "[selective-tests] project config: ${config_path} (${location})"
            else
              echo "::warning::selective-tests: project config found via ${location} at ${config_path} (not the checkout root). Selective tests will run; if you expected the empty-matrix branch, check your checkout layout."
            fi
          else
            echo "found=false" >> "$GITHUB_OUTPUT"
            echo "config_path=${rel}" >> "$GITHUB_OUTPUT"
            echo "[selective-tests] no project config found — emitting empty matrix."
          fi

      - name: Determine promotion event
        id: promotion
        run: |
SELECTIVE_EOF

  # Append the promotion step with the final branch interpolated.
  # This block is written separately because it contains a shell variable.
  cat >> "$_tmp" <<SELECTIVE_PROMO_EOF
          config_path="\${{ steps.cfg.outputs.config_path }}"
          final_branch="${final_branch}"
          base="\${{ github.event.pull_request.base.ref || github.ref_name }}"
          if [[ "\$base" == "\$final_branch" ]]; then
            echo "is_promotion=true" >> "\$GITHUB_OUTPUT"
          else
            echo "is_promotion=false" >> "\$GITHUB_OUTPUT"
          fi
SELECTIVE_PROMO_EOF

  cat >> "$_tmp" <<'SELECTIVE_REST_EOF'

      - name: Collect changed files
        id: changes
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            git diff --name-only "${{ github.event.pull_request.base.sha }}" "${{ github.sha }}" > changed-files.txt
          else
            git diff --name-only "${{ github.event.before }}" "${{ github.sha }}" > changed-files.txt
          fi
          echo "files=changed-files.txt" >> "$GITHUB_OUTPUT"

      - name: Run selective-test-driver
        id: driver
        run: |
          config_path="${{ steps.cfg.outputs.config_path }}"
          if [[ "${{ steps.cfg.outputs.found }}" != "true" ]]; then
            echo "[NOTICE] selective-tests: no project-config found — emitting empty matrix"
            echo "matrix={\"include\":[]}" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          driver_extra=()
          if [[ "${{ steps.promotion.outputs.is_promotion }}" == "true" ]]; then
            driver_extra+=(--event promotion-push)
          fi
          matrix_json="$(.gaia/ci-scripts/selective-test-driver.sh \
            --config "$config_path" \
            --trigger "${{ steps.trigger.outputs.type }}" \
            "${driver_extra[@]}" \
            --files-from "${{ steps.changes.outputs.files }}")"
          echo "matrix=${matrix_json}" >> "$GITHUB_OUTPUT"

  test:
    name: test (${{ matrix.stack }})
    needs: plan
    if: needs.plan.outputs.matrix != '{"include":[]}' && needs.plan.outputs.matrix != ''
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.plan.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Run stack tests
        run: |
          config_path="${{ needs.plan.outputs.config_path }}"
          [[ -n "$config_path" ]] || config_path=".gaia/config/project-config.yaml"
          .gaia/ci-scripts/run-stack-tests.sh \
            --config "$config_path" \
            "${{ matrix.stack }}"
SELECTIVE_REST_EOF

  mv "$_tmp" "$wf"
  _log "wrote $wf (multi-stack selective-tests)"
}

# ---------------------------------------------------------------------------
# _generate_release_workflow CONFIG PROJECT_ROOT — emit gaia-release.yml
# Per-component release scoped to the affected component set.
# ---------------------------------------------------------------------------
_generate_release_workflow() {
  local config="$1"
  local project_root="$2"

  local wf_dir="$project_root/.github/workflows"
  mkdir -p "$wf_dir"
  local wf="$wf_dir/gaia-release.yml"

  local _tmp
  _tmp="$(mktemp "${wf}.XXXXXX")"

  # Read stack names for documentation in the workflow
  local stack_names
  stack_names="$(_read_stack_names "$config" | tr '\n' ',' | sed 's/,$//')"

  cat > "$_tmp" <<RELEASE_EOF
# Generated by /gaia-ci-setup — per-component release workflow.
# Scopes version-bump and release to affected components only.
# Components: ${stack_names}
name: gaia-release
on:
  workflow_dispatch:
    inputs:
      mode:
        description: "prepare or publish"
        required: true
        default: prepare
        type: choice
        options:
          - prepare
          - publish
      component:
        description: "Component to release (blank = all affected)"
        required: false
        type: string
jobs:
  plan:
    name: Determine affected components
    runs-on: ubuntu-latest
    outputs:
      matrix: \${{ steps.resolve.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Resolve affected components
        id: resolve
        run: |
          config_path=".gaia/config/project-config.yaml"
          if [[ -f ".gaia/ci-config.yaml" ]]; then
            config_path=".gaia/ci-config.yaml"
          fi
          component="\${{ github.event.inputs.component }}"
          if [[ -n "\$component" ]]; then
            echo "matrix={\"include\":[{\"stack\":\"\$component\"}]}" >> "\$GITHUB_OUTPUT"
          else
            # Use the affected-set detector to scope the release
            affected="\$(.gaia/ci-scripts/detect-affected.sh \\
              --config "\$config_path" \\
              --event promotion-push)"
            matrix="\$(echo "\$affected" | .gaia/ci-scripts/generate-pipeline.sh \\
              --config "\$config_path")"
            echo "matrix=\$matrix" >> "\$GITHUB_OUTPUT"
          fi

  release:
    name: release (\${{ matrix.stack }})
    needs: plan
    if: needs.plan.outputs.matrix != '{"include":[]}' && needs.plan.outputs.matrix != ''
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: \${{ fromJSON(needs.plan.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release component
        run: |
          # TODO(operator): wire your release command here — e.g.
          # version-bump.js scoped to \${{ matrix.stack }}, or
          # your project's release tooling. The lines below are
          # scaffolding placeholders that do nothing.
          echo "Releasing component: \${{ matrix.stack }}"
          echo "Mode: \${{ github.event.inputs.mode }}"
RELEASE_EOF

  mv "$_tmp" "$wf"
  _log "wrote $wf (per-component release)"
}

# ---------------------------------------------------------------------------
# _vendor_engine_scripts CONFIG PROJECT_ROOT — vendor engine scripts to
# .gaia/ci-scripts/ with a sha256 drift manifest.
# ---------------------------------------------------------------------------
_vendor_engine_scripts() {
  local config="$1"
  local project_root="$2"

  local target_dir="$project_root/.gaia/ci-scripts"
  mkdir -p "$target_dir"

  # List of engine scripts to vendor (relative to _ENGINE_SCRIPTS_DIR)
  local scripts
  scripts="selective-test-driver.sh
detect-affected.sh
generate-pipeline.sh
cross-refs-walk.sh
reconcile-stale-graph.sh
apply-test-policy.sh
run-stack-tests.sh
run-with-retry.sh
gen-ci-config.sh"

  local manifest="$target_dir/MANIFEST.sha256"
  : > "$manifest"

  local script_name src dst
  while IFS= read -r script_name; do
    [ -z "$script_name" ] && continue
    src="$_ENGINE_SCRIPTS_DIR/$script_name"
    dst="$target_dir/$script_name"
    if [ -f "$src" ]; then
      cp "$src" "$dst"
      chmod +x "$dst"
      # Compute sha256 for drift detection
      local hash
      hash="$(shasum -a 256 "$src" | cut -d' ' -f1)"
      printf '%s  %s\n' "$hash" "$script_name" >> "$manifest"
    fi
  done <<EOF
$scripts
EOF

  # Also vendor the lib/ directory if it exists (resolve-file-to-stack.sh etc.)
  if [ -d "$_ENGINE_SCRIPTS_DIR/lib" ]; then
    mkdir -p "$target_dir/lib"
    local lib_file
    for lib_file in "$_ENGINE_SCRIPTS_DIR"/lib/*.sh; do
      [ -f "$lib_file" ] || continue
      local lib_name
      lib_name="$(basename "$lib_file")"
      cp "$lib_file" "$target_dir/lib/$lib_name"
      chmod +x "$target_dir/lib/$lib_name"
      local hash
      hash="$(shasum -a 256 "$lib_file" | cut -d' ' -f1)"
      printf '%s  %s\n' "$hash" "lib/$lib_name" >> "$manifest"
    done
  fi

  _log "wrote engine scripts to $target_dir ($(wc -l < "$manifest" | tr -d ' ') files)"
}

# ---------------------------------------------------------------------------
# Arg parsing — extended to support --config for multi-stack detection.
# Wrapped in a function for sourced-mode testability.
# ---------------------------------------------------------------------------
_parse_args() {
  PROVIDER=""
  STACK=""
  PROJECT_ROOT=""
  CONFIG=""

  while [ $# -gt 0 ]; do
    case "$1" in
      --provider)     PROVIDER="${2:-}"; shift 2 ;;
      --stack)        STACK="${2:-}"; shift 2 ;;
      --project-root) PROJECT_ROOT="${2:-}"; shift 2 ;;
      --config)       CONFIG="${2:-}"; shift 2 ;;
      -h|--help)
        cat <<EOF
$SCRIPT_NAME — deterministic CI workflow generator for /gaia-ci-setup Step 8

Usage:
  $0 --provider <ci> --stack <stack> --project-root <dir>
  $0 --provider <ci> --config <config> --project-root <dir>

Supported providers: github-actions
Supported stacks (single-stack mode): python, node, go, jvm

When --config points to a project config with 2+ stacks, generates the
multi-stack selective-tests workflow, per-component release workflow, and
vendors engine scripts under .gaia/ci-scripts/.

Single-stack configs (or explicit --stack) produce only gaia-pre-merge.yml.
EOF
        exit 0 ;;
      *) _die "unknown flag: $1" ;;
    esac
  done
}

# ---------------------------------------------------------------------------
# _generate_single_stack — the original single-stack gaia-pre-merge.yml path
# ---------------------------------------------------------------------------
_generate_single_stack() {
  [ -n "$PROVIDER" ]     || _die "--provider required (try: github-actions)"
  [ -n "$STACK" ]        || _die "--stack required (try: python, node, go, jvm)"
  [ -n "$PROJECT_ROOT" ] || _die "--project-root required"
  [ -d "$PROJECT_ROOT" ] || _die "project root does not exist: $PROJECT_ROOT"

  if [ "$PROVIDER" != "github-actions" ]; then
    _warn "provider '$PROVIDER' is not yet supported by the deterministic generator (supported: github-actions)"
    _warn "the init-generated stub remains in place; hand-edit it via /gaia-ci-setup interactive mode"
    exit 1
  fi

  case "$STACK" in
    python|node|go|jvm) : ;;
    *) _warn "stack '$STACK' is not yet supported by the deterministic generator (supported: python, node, go, jvm)"
       _warn "the init-generated stub remains in place; hand-edit it via /gaia-ci-setup interactive mode"
       exit 1 ;;
  esac

  local WORKFLOW="$PROJECT_ROOT/.github/workflows/gaia-pre-merge.yml"
  mkdir -p "$(dirname "$WORKFLOW")"

  # Refuse to overwrite a workflow that already exists AND lacks the
  # init-stub marker line (operators may have customised it).
  if [ -f "$WORKFLOW" ] && ! grep -qF 'GAIA pre-merge gate is not yet configured' "$WORKFLOW"; then
    _warn "$WORKFLOW already exists and does not contain the init-stub marker — refusing to overwrite (use /gaia-ci-setup --regenerate to force)"
    exit 0
  fi

  local _run_block
  case "$STACK" in
    python)
      _run_block='      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          if [ -f pyproject.toml ]; then pip install -e ".[dev]" || pip install .; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Test
        run: |
          if command -v pytest >/dev/null; then pytest -q; else python -m unittest discover -v; fi'
      ;;
    node)
      _run_block='      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install
        run: |
          if [ -f pnpm-lock.yaml ]; then npm install -g pnpm && pnpm install --frozen-lockfile
          elif [ -f yarn.lock ]; then yarn install --frozen-lockfile
          else npm ci || npm install; fi
      - name: Test
        run: |
          if [ -f pnpm-lock.yaml ]; then pnpm test
          elif [ -f yarn.lock ]; then yarn test
          else npm test; fi'
      ;;
    go)
      _run_block='      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Build
        run: go build ./...
      - name: Test
        run: go test -v ./...'
      ;;
    jvm)
      _run_block='      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Test
        run: |
          if [ -f pom.xml ]; then mvn -B test
          elif [ -f build.gradle ] || [ -f build.gradle.kts ]; then ./gradlew test || gradle test
          else echo "no maven/gradle marker found" >&2; exit 1; fi'
      ;;
  esac

  # Atomic write via tempfile + mv.
  local _tmp
  _tmp="$(mktemp "${WORKFLOW}.XXXXXX")"
  cat > "$_tmp" <<EOF
# Generated by /gaia-ci-setup.
# Pre-merge quality gate — runs the project's test suite on every pull
# request against main / staging. Hand-edits are preserved on re-run UNLESS
# the file still carries the init-stub marker (the prior no-op placeholder
# /gaia-init seeds); in that case /gaia-ci-setup regenerates this workflow
# without prompting. Customise the matrix or add lint steps in the
# sibling \`gaia-pre-merge.user-steps.yml\` companion (preserved verbatim
# on regeneration).
name: gaia-pre-merge
on:
  pull_request:
    branches: [main, staging]
jobs:
  gaia-gates:
    name: GAIA pre-merge gates
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
$_run_block
EOF
  mv "$_tmp" "$WORKFLOW"

  _log "wrote $WORKFLOW (stack=$STACK, provider=$PROVIDER)"
}

# ---------------------------------------------------------------------------
# main — entry point
# ---------------------------------------------------------------------------
main() {
  _parse_args "$@"

  [ -n "$PROJECT_ROOT" ] || _die "--project-root required"
  [ -d "$PROJECT_ROOT" ] || _die "project root does not exist: $PROJECT_ROOT"

  # Determine if this is a multi-stack project
  local stack_count=0
  if [ -n "$CONFIG" ] && [ -f "$CONFIG" ]; then
    stack_count="$(count_config_stacks "$CONFIG")"
  fi

  if [ "$stack_count" -gt 1 ]; then
    # Multi-stack path: generate selective-tests + release + engine scripts
    [ -n "$PROVIDER" ] || PROVIDER="github-actions"

    if [ "$PROVIDER" != "github-actions" ]; then
      _warn "provider '$PROVIDER' is not yet supported for multi-stack generation (supported: github-actions)"
      exit 1
    fi

    _log "multi-stack project detected ($stack_count stacks) — generating selective-tests + release workflows"
    _generate_selective_tests "$CONFIG" "$PROJECT_ROOT"
    _generate_release_workflow "$CONFIG" "$PROJECT_ROOT"
    _vendor_engine_scripts "$CONFIG" "$PROJECT_ROOT"
  else
    # Single-stack path: existing behavior (requires --stack)
    if [ -z "$STACK" ] && [ -n "$CONFIG" ] && [ -f "$CONFIG" ] && [ "$stack_count" -eq 1 ]; then
      # Auto-detect stack language from config
      STACK="$(awk '
      BEGIN { in_stacks = 0 }
      /^stacks:/ { in_stacks = 1; next }
      in_stacks && /^[a-zA-Z_]/ { exit }
      in_stacks && /language:/ {
        val = $0
        sub(/.*language:[[:space:]]*/, "", val)
        gsub(/^[[:space:]]+/, "", val)
        gsub(/[[:space:]]+$/, "", val)
        gsub(/^"/, "", val); gsub(/"$/, "", val)
        print val
        exit
      }
      ' "$CONFIG")"
    fi
    _generate_single_stack
  fi

  exit 0
}

# Main-guard: only invoke main when executed directly (not when sourced).
# Sourcing must expose public functions without side-effects.
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
  main "$@"
fi
