#!/usr/bin/env bash
# issue-1293-brownfield-manifest-caller.bats
#
# The test-environment-manifest helper stamps the generated manifest header
# with the calling skill (via GAIA_TEST_ENV_CALLER, default /gaia-bridge-enable).
# /gaia-brownfield Phase 5 invoked the helper WITHOUT setting that var, so the
# brownfield-generated manifest header read "Auto-generated by
# /gaia-bridge-enable" — misleading on a brownfield run. The fix sets
# GAIA_TEST_ENV_CALLER=/gaia-brownfield in the Phase 5 invocation.

load 'test_helper.bash'

setup() {
  common_setup
  PLUGIN_ROOT="$(cd "$BATS_TEST_DIRNAME/.." && pwd)"
  SKILL_MD="$PLUGIN_ROOT/skills/gaia-brownfield/SKILL.md"
  HELPER="$PLUGIN_ROOT/scripts/lib/test-environment-manifest.sh"
}
teardown() { common_teardown; }

@test "issue-1293: brownfield Phase 5 sets GAIA_TEST_ENV_CALLER=/gaia-brownfield" {
  grep -qF 'GAIA_TEST_ENV_CALLER=/gaia-brownfield' "$SKILL_MD"
}

@test "issue-1293: the helper honors GAIA_TEST_ENV_CALLER in the manifest header" {
  # End-to-end: the generated manifest header reflects the caller.
  local proj; proj="$(mktemp -d "$BATS_TEST_TMPDIR/bf.XXXXXX")"
  printf '[tool.pytest.ini_options]\n' > "$proj/pyproject.toml"
  GAIA_TEST_ENV_CALLER=/gaia-brownfield \
    bash "$HELPER" --target "$proj" --write >/dev/null 2>&1 || true
  local manifest
  manifest="$(find "$proj" -name 'test-environment.yaml' | head -1)"
  [ -n "$manifest" ] || skip "helper did not write a manifest in this environment"
  grep -qF '/gaia-brownfield' "$manifest"
  ! grep -qF 'Auto-generated by /gaia-bridge-enable' "$manifest"
}
