#!/usr/bin/env bats
# retirement-fixture-traceability.bats -- asserts every deleted fixture and
# suite is absent from the tree, and that no surviving test or CI config
# references a deleted path.

setup() {
  PLUGIN_ROOT="$(cd "$BATS_TEST_DIRNAME/.." && pwd)"
  REPO_ROOT="$(cd "$PLUGIN_ROOT/../.." && pwd)"
  # Split-fragment provider literal -- never contiguous in this file
  _PROVIDER="$(printf '%s%s' 'fig' 'ma')"

  # Deleted file basenames (used by both tests).
  # The traceability evidence (each basename to its inventory row) is
  # recorded in the story's Dev Agent Record / completion notes at Step 8,
  # not asserted here, because the inventory lives outside gaia-public and
  # CI checks out only gaia-public.
  DELETED_BASENAMES=(
    "design-tokens.json"
    "component-specs.yaml"
    "mcp-trace.json"
    "vcp-ux-06.bats"
    "vcp-ux-import.bats"
    "vcp-ux-generate.bats"
    "gaia-dev-story-${_PROVIDER}-degrade.bats"
    "e28-s113-edge-cases-${_PROVIDER}-conversion.bats"
  )

  # Deleted paths relative to the repo root.
  DELETED_RELPATHS=(
    "plugins/gaia/tests/fixtures/${_PROVIDER}-import/design-tokens.json"
    "plugins/gaia/tests/fixtures/${_PROVIDER}-import/component-specs.yaml"
    "plugins/gaia/tests/fixtures/${_PROVIDER}-import/mcp-trace.json"
    "plugins/gaia/tests/vcp-ux-06.bats"
    "plugins/gaia/tests/vcp-ux-import.bats"
    "plugins/gaia/tests/vcp-ux-generate.bats"
    "tests/skills/gaia-dev-story-${_PROVIDER}-degrade.bats"
    "tests/skills/e28-s113-edge-cases-${_PROVIDER}-conversion.bats"
  )

  # The fixture directory itself.
  DELETED_DIR="plugins/gaia/tests/fixtures/${_PROVIDER}-import"
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# _is_deleted_basename <basename>
# Returns 0 if the basename is in DELETED_BASENAMES.
_is_deleted_basename() {
  local target="$1"
  for dbn in "${DELETED_BASENAMES[@]}"; do
    [ "$target" = "$dbn" ] && return 0
  done
  return 1
}

# _grep_references <search_term>
# Greps for search_term across test roots and CI workflows, excluding self
# and the component manifest (regenerated by tagger). Prints only surviving
# (non-deleted) files that contain a match.
_grep_references() {
  local term="$1"
  local self_name
  self_name="$(basename "${BATS_TEST_FILENAME:-retirement-fixture-traceability.bats}")"

  local hits
  hits="$(grep -rlF "$term" \
    "$PLUGIN_ROOT/tests/" \
    "$REPO_ROOT/tests/" \
    "$REPO_ROOT/.github/workflows/" \
    2>/dev/null \
    | grep -vF "$self_name" \
    | grep -vF 'component-manifest.tsv' || true)"

  [ -z "$hits" ] && return 0
  while IFS= read -r hitfile; do
    _is_deleted_basename "$(basename "$hitfile")" || printf '%s\n' "$hitfile"
  done <<< "$hits"
}

# ---------------------------------------------------------------------------
# AC3 — each deleted fixture/suite is absent from the tree
# ---------------------------------------------------------------------------

@test "(AC3) each deleted fixture and suite is absent" {
  local still_present=()
  for relpath in "${DELETED_RELPATHS[@]}"; do
    [ -e "$REPO_ROOT/$relpath" ] && still_present+=("$relpath")
  done
  [ -d "$REPO_ROOT/$DELETED_DIR" ] && still_present+=("$DELETED_DIR/")

  if [ ${#still_present[@]} -gt 0 ]; then
    printf 'Still present (delete these files to satisfy AC3):\n'
    printf '  %s\n' "${still_present[@]}"
    return 1
  fi
}

# ---------------------------------------------------------------------------
# AC-EC5 — no surviving file references a deleted fixture or suite path
# ---------------------------------------------------------------------------

@test "(AC-EC5) no surviving file references a deleted path" {
  local all_hits=""

  for bn in "${DELETED_BASENAMES[@]}"; do
    local refs
    refs="$(_grep_references "$bn")"
    [ -n "$refs" ] && all_hits="${all_hits}${bn} referenced by:\n${refs}\n"
  done

  # Also check the deleted directory name.
  local dir_refs
  dir_refs="$(_grep_references "${_PROVIDER}-import")"
  [ -n "$dir_refs" ] && all_hits="${all_hits}${_PROVIDER}-import/ referenced by:\n${dir_refs}\n"

  if [ -n "$all_hits" ]; then
    printf 'Surviving files still reference deleted paths (remove these references):\n'
    printf '%b' "$all_hits"
    return 1
  fi
}
